### ISSUE TITLE
Add option to choose a.m./p.m. or 24-hour notation

### ISSUE THREAD

**Issue by ryonakano** [elementary/greeter#111]
["Wingpanel Date & Time Indicator"](https://github.com/elementary/wingpanel-indicator-datetime) has a option to choose a.m./p.m. or 24-hour notation in System Setting. However, "Greeter" does not. So, is it possible to add option to choose a.m./p.m. or 24-hour notation in "Greeter?" Or, is it possible to sync the choice of the notation between "Wingpanel Date & Time Indicator" and "Greeter?"

**Comment by jlnr** [comment]
Related: #53

**Comment by ryonakano** [comment]
I'm so sorry, there are same issue: #52
