### ISSUE TITLE
Wrong Screen Resolution on Dual Monitor

### ISSUE THREAD

**Issue by btd1337** [elementary/greeter#112]
Notebook resolution, it's ok

![photo_2018-05-23_13-40-05](https://user-images.githubusercontent.com/11943860/40439054-33438a62-5e90-11e8-8fb5-f5aacc4ae6f8.jpg)

External monitor, it's wrong
![photo_2018-05-23_13-40-24](https://user-images.githubusercontent.com/11943860/40439059-36733980-5e90-11e8-8a38-ed4c4ffbf8c5.jpg)

**Comment by peteruithoven** [comment]
Could you verify if this is this an issue with the latest (unreleased) version?

**Comment by peteruithoven** [comment]
Looks like this is a duplicate of #27
