### ISSUE TITLE
suspend when inactive on lock screen not integrate with Switchboard power

### ISSUE THREAD

**Issue by torikulhabib** [elementary/greeter#121]
![screenshot from 2018-06-21 18-12-42](https://user-images.githubusercontent.com/26135527/41716151-b3c2cc7e-757f-11e8-89be-342ba59a2b4c.png)

i try lock screen with "dm-tool lock"
before it, i set "suspend when inactive" (never)
but on lock screen after turn off screen least 5 minute laptop suspend
switchboard power on lock screen not working

**Comment by mdh34** [comment]
@torikulhabib what system are you running?

**Comment by torikulhabib** [comment]
![screenshot from 2018-06-21 19-07-36](https://user-images.githubusercontent.com/26135527/41718177-6ea1ec54-7586-11e8-960c-7103c1b448ff.png)
