### ISSUE TITLE
Display the keyboard layout indicator also in the topbar of Greeter

### ISSUE THREAD

**Issue by Saeniel** [elementary/greeter#128]
Display current language on start screen when user have to type his password.
Sometimes it's kinda confusing when you don't know what is in password input.

**Comment by ryonakano** [comment]
> Display current language

@Saeniel Do you mean clarify characters in the password?

**Comment by Saeniel** [comment]
@ryonakano 
I mean something like this icon. 
![image](https://user-images.githubusercontent.com/22329568/42242543-e740cf6a-7f16-11e8-99e5-616d7b6ab0fd.png)

**Comment by ryonakano** [comment]
@Saeniel So you mean display the keyboard layout indicator also in the topbar of Greeter, right?

**Comment by Saeniel** [comment]
@ryonakano yes, you are right.

**Comment by ryonakano** [comment]
@Saeniel I see.
So, would you change the title of this issue? I think we should change it to more clear one because I think the current one is a little abstract. For example, "Display the keyboard layout indicator also in the topbar of Greeter" or something like that.

**Comment by Saeniel** [comment]
@ryonakano 
OK
Sorry for confusing, English is not my native language.

**Comment by ryonakano** [comment]
@Saeniel That's all right, neither am I :smile:

**Comment by ryonakano** [comment]
Now I found this issue may be a duplication of https://github.com/elementary/wingpanel-indicator-keyboard/issues/5

**Comment by jeremypw** [comment]
It is possible to get locked out of your computer if you accidentally switch keyboard layouts just before logging out.  Typing the normal password may then not work.  Moreover the usal shortcut `<Alt><Shift>` does not work in greeter.

**Comment by henricazottes** [comment]
I'm also using a keyboard layout different from the one present after installation (which is used on greeter). This fix would be awesome :)

**Comment by ryonakano** [comment]
Should be fixed in latest odin daily
