### ISSUE TITLE
Refresh file manager

### ISSUE THREAD

**Issue by Saeniel** [elementary/greeter#129]
1) Open file manager in download folder, for example
2) Download some file from internet
3) You can't see that file in file manager
This situation is not about just downloaded file. After "tar xf file.tar.xz" I can't see extracted files too.

Issue: refresh file manager after changes.

**Comment by danrabbit** [comment]
This repo is for the lock and login screen. You might be looking for https://github.com/elementary/files

Closing this as "Out of scope" since this issue is not about the greeter
