### ISSUE TITLE
Add orientation lock to greeter.

### ISSUE THREAD

**Issue by arshubham** [elementary/greeter#130]
Since greeter doesn't respect the user settings for orientation lock, it would be great if the same could be added to greeter too. Both GDM and Gnome shell has orientation lock exposed in the indicator. The setting should be exposed not only on the basis of presence on touchscreen but if possible always. Due to a bug most of the HP laptops are affected, i.e. if not kept in upright direction at boot. the screen rotates. https://github.com/systemd/systemd/issues/7151 . I can fix this after login by changing orientation lock gsettings but it still affects the greeter.

**Comment by pcputta** [comment]
Every time the system goes to sleep and whenever we try logging back the login screen orientation is rotated and after logging in the display is inverted. I am using HP-ProBook-4530s never experienced this in Freya but getting this since i installed Juno
