### ISSUE TITLE
No panel shown at all

### ISSUE THREAD

**Issue by arshubham** [elementary/greeter#133]
Happens on Juno beta 1 after https://github.com/elementary/greeter/pull/127 . No panel is shown at all even after reboot.

**Comment by danrabbit** [comment]
Fixed in 9ee72f617ad244256c74999f484ac5eb937fdc0b

**Comment by danrabbit** [comment]
Ah just realized you are referencing this commit. You need both greeter master and wingpanel master in order for this to work

**Comment by arshubham** [comment]
@danrabbit  I am on daily ppa, I verified from launchpad that the wingpanel and greeter was built after the commits before reporting it.
