### ISSUE TITLE
Compositor spawn Greeter's Window in the secondary monitor

### ISSUE THREAD

**Issue by leonardo-lemos** [elementary/greeter#141]
When using a secondary monitor, Wingpanel and cursor is spawned in the primary monitor, although the Greeter Window is spawned in the secondary monitor. Those components should be all in the primary monitor.

![photo_2018-07-11_23-37-52](https://user-images.githubusercontent.com/828559/42609615-c5f9bf4e-8563-11e8-94f0-e58f72c8bc1f.jpg)

**Comment by croozey** [comment]
Nothing to add - just confirming this is happening to me also.

**Comment by toshe** [comment]
Is that #65?

**Comment by peteruithoven** [comment]
Seems like a duplicate of #65 indeed
