### ISSUE TITLE
Dynamic user

### ISSUE THREAD

**Issue by peteruithoven** [elementary/greeter#157]
Since I upgraded to Juno I sometimes get an extra "Dynamic user" in the greeter. Is there anyway to track down where that comes from? I haven't found a way to reproduce it. 
![img_20180921_193704-2000](https://user-images.githubusercontent.com/523210/45897634-f886c400-bdd7-11e8-8631-65092ba87908.jpg)

![screenshot from 2018-10-01 14 26 35](https://user-images.githubusercontent.com/523210/46288456-08e03100-c586-11e8-8354-63d26502b689.png)

**Comment by peteruithoven** [comment]
This doesn't seem to be a elementary OS specific issue: https://askubuntu.com/questions/1035203/why-is-a-dynamic-user-appearing-in-my-users.

**Comment by peteruithoven** [comment]
Looks like it's new SystemD functionality: http://0pointer.net/blog/dynamic-users-with-systemd.html
Some discussion on it: https://bbs.archlinux.org/viewtopic.php?id=238704
Reading those I'm pretty sure this user should be hidden.

**Comment by peteruithoven** [comment]
@jlnr: 
> It looks like hiding all users with a shell ending in "/nologin" would do the trick - https://github.com/CanonicalLtd/lightdm/pull/38/files 

I've manually edited my `users.conf` to see if it returns. Not sure in which repo we can make this change or we should open an issue in. I couldn't find the `users.conf` in https://github.com/elementary/default-settings

**Comment by peteruithoven** [comment]
@codygarver has proposed a merge request at debian which was merged:
https://salsa.debian.org/xfce-extras-team/lightdm/merge_requests/1

**Comment by peteruithoven** [comment]
Even though my `/etc/lightdm/users.conf` file contains `/sbin/nologin`, the Dynamic User appeared again.

**Comment by arshubham** [comment]
I have also starting to experience this usually after using my laptop for a few hours. Goes away after a reboot. Might be good to just add it to a blacklist as a workaround.

**Comment by peteruithoven** [comment]
I've not seen this Dynamic user since I've installed the `master` version.
