### ISSUE TITLE
Overlapping time/date possition!

### ISSUE THREAD

**Issue by teTorrian** [elementary/greeter#159]
![img_20180925_095432_resized_20180925_095920976](https://user-images.githubusercontent.com/4487769/46000906-36bb0680-c0aa-11e8-9bcc-b47382ecab19.jpg)

As you can see, time/date position acts weird. Maybe the longer german word for "morning" is guilty. Why not leaving the terms "pm" and "am"? A much simpler and global description for that.

**Comment by jlnr** [comment]
If your locale is set to German/de_DE, then this is a duplicate of #52, because the greeter shouldn't be using AM/PM in the first place.

**Comment by Jason5679** [comment]
Same problem here, but my clock is too far right. (tested on both of my computers)
