### ISSUE TITLE
Greeter does not respect power saving settings

### ISSUE THREAD

**Issue by DanyGee** [elementary/greeter#161]
Noticed, although I disabled any power savings in System Settings->Power...
![screenshot from 2018-09-28 19 25 36 2x](https://user-images.githubusercontent.com/26818551/46223856-d3083600-c354-11e8-9248-49823fd8ce03.png)
...that Greeter suspends my machine after some time period. Don't know the exact time period, but the machine gets suspended.

I'm pretty sure, LOKI didn't suspend my PC while locked.
Please take a look into this. If this is by design, please remember that not every user likes to suspend his machine, thus please provide an option to switch it off.

My system:
```
System:    Host: elementary-os-beta2 Kernel: 4.15.0-34-generic x86_64 bits: 64 compiler: gcc v: 7.3.0 
           Desktop: Pantheon Distro: elementary OS 5.0 Juno base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop Mobo: ASUSTeK model: Z170-DELUXE v: Rev 1.xx serial: <filter> 
           UEFI [Legacy]: American Megatrends v: 3504 date: 06/29/2017 
CPU:       Topology: Quad Core model: Intel Core i7-6700K bits: 64 type: MT MCP arch: Skylake-S rev: 3 
           L2 cache: 8192 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 64128 
           Speed: 800 MHz min/max: 800/4300 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 801 5: 800 6: 800 
           7: 801 8: 800 
Graphics:  Device-1: NVIDIA GP104 [GeForce GTX 1080] driver: nvidia v: 390.48 bus ID: 01:00.0 
           Display: x11 server: X.Org 1.19.6 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 3840x2160~60Hz 
           OpenGL: renderer: GeForce GTX 1080/PCIe/SSE2 v: 4.6.0 NVIDIA 390.48 direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-H HD Audio driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           Device-2: NVIDIA GP104 High Definition Audio driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           Sound Server: ALSA v: k4.15.0-34-generic 
Network:   Device-1: Intel Ethernet I219-V driver: e1000e v: 3.2.6-k port: f000 bus ID: 00:1f.6 
           IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Broadcom Limited BCM4360 802.11ac Wireless Network Adapter driver: bcma-pci-bridge v: N/A 
           port: e000 bus ID: 07:00.0 
           Device-3: Intel I211 Gigabit Network driver: igb v: 5.4.0-k port: c000 bus ID: 0b:00.0 
           IF: enp11s0 state: down mac: <filter> 
Drives:    Local Storage: total: 2.34 TiB used: 35.86 GiB (1.5%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 850 PRO 256GB size: 238.47 GiB 
           ID-2: /dev/sdb vendor: Samsung model: SSD 850 PRO 1TB size: 953.87 GiB 
           ID-3: /dev/sdc vendor: Crucial model: CT1050MX300SSD1 size: 978.09 GiB 
           ID-4: /dev/sdd vendor: Kingston model: SH100S3120G size: 111.79 GiB 
           ID-5: /dev/sde vendor: Kingston model: SV300S37A120G size: 111.79 GiB 
Partition: ID-1: / size: 109.53 GiB used: 35.86 GiB (32.7%) fs: ext4 dev: /dev/sde1 
Sensors:   System Temperatures: cpu: 36.0 C mobo: N/A gpu: nvidia temp: 54 C 
           Fan Speeds (RPM): cpu: 0 gpu: nvidia fan: 0% 
Info:      Processes: 254 Uptime: 12m Memory: 31.35 GiB used: 1.42 GiB (4.5%) Init: systemd runlevel: 5 
           Compilers: gcc: 7.3.0 Shell: bash v: 4.4.19 inxi: 3.0.25
```

**Comment by DanyGee** [comment]
Did some tests :desktop_computer: 

Edited the **/etc/lightdm/io.elementary.greeter.conf**
Although there's a hashed out line:
`#screensaver-timeout=60`
The screensaver still enables itself after 60 s.
Then, after 10 min the signal to the screen gets killed.
And after another 5 minutes (15 min from lockdown) the machine suspends.

Unhashing the line, and changing the timer...
`screensaver-timeout=9999` (accepts 4 digits max, 5 digits and more break lightdm killing the signal completely)
...results in the screensaver does not trigger itself...but after 10 mins the signal to the screen still gets killed and after another 5 mins the machine suspends.

That means, the default power saving settings seem to be hardcoded somewhere else :thinking:

**Comment by DanyGee** [comment]
I managed to disable suspend mode through following workaround...
```
sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
       
Created symlink /etc/systemd/system/sleep.target → /dev/null.
Created symlink /etc/systemd/system/suspend.target → /dev/null.
Created symlink /etc/systemd/system/hibernate.target → /dev/null.
Created symlink /etc/systemd/system/hybrid-sleep.target → /dev/null.
```
...and tested it for couple of hours on locked session - after 10 min the screen went completely off, but the machine did not suspend :+1: 

Tried this...
`xset s off s noblank -dpms`
... to disable screensaver and screen off features, but they seem to be ignored - the screen turns off in 10 mins after locking the session.
Any other ideas, folks? :bulb:

**Comment by DanyGee** [comment]
Found the guilty one. Looks like the 10 min screen-off is default for X server.
Adding following options to their corresponding sections in **/etc/X11/xorg.conf**...
```
Section "Monitor"
    Option "DPMS" "false"
...
Section "ServerLayout"
...
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime"     "0"
    Option "BlankTime"   "0"
...
```
...finally did turn off that anoying screen-off feature.
Now when locked in greeter, after passing 10 mins mark the screen still stays ON :tada:

**Comment by Schyken** [comment]
I'd like to note that I'm having the same issue with Juno (post-release). Every user on the machine has the suspend mode set to 'Never' and the system does not respect the users' choice. This has consistently interfered with my work as things left running get cut off by system suspend. I'll try to use some of the redirect tips above.

**Comment by donadigo** [comment]
@Schyken @DanyGee did you upgrade to Juno stable? The issue was supposedly fixed in the power plug (see https://github.com/elementary/switchboard-plug-power/issues/89). If it still persists, please comment.

**Comment by DanyGee** [comment]
Updated my both machines to Juno today.
On both the same issue exists.
Had to apply the same workarounds as above.

**Comment by leonidasv** [comment]
With Intel HD Graphics I get the same suspending behaviour, but the corners render smoothly.

**Comment by cassidyjames** [comment]
Marking as high priority since this affects a lot of people and we're getting a lot of duplicate reports about it.

**Comment by eljefuri** [comment]
Confirming that this same issue is found on seemingly all of the 10+ notebook installs that I am supporting.

**Comment by rbnlffl** [comment]
Confirming, too. And as I'm using eOS Juno on my small server at home, this bug affects me _massively_. Hope a fix is underway soon! People on reddit are starting to freak out, as well.

**Comment by cassidyjames** [comment]
**Please do not comment to confirm issues.** Using the built-in :+1: reaction is sufficient to let us know you are affected, and you can subscribe to updates using the built-in Subscribe feature. Commenting to confirm just spams other users who are interested in the resolution.

**Comment by danrabbit** [comment]
Removing from the 5.1 milestone since this issue also effects the clutter greeter

**Comment by gvansanden** [comment]
Still happening on all my machines, is there a fix planned

**Comment by minhdanh** [comment]
Upgraded the system some days ago but this issue still happens for me. Set `Suspend when inactive for` to `Never`, but the system will go to sleep just about 30 mins later.

**Comment by jo3d3v** [comment]
> Upgraded the system some days ago but this issue still happens for me. Set `Suspend when inactive for` to `Never`, but the system will go to sleep just about 30 mins later.

I think no new release has been released since PR #343 has been merged. I think you have to wait for an new release to get the fix done for you.

**Comment by minhdanh** [comment]
Interesting. Is there a way to track which PRs or commits are included in a release?

**Comment by jo3d3v** [comment]
> Interesting. Is there a way to track which PRs or commits are included in a release?

You have to look at the tag (https://github.com/elementary/greeter/commits/5.0.1)  and the master branch (https://github.com/elementary/greeter/commits/master), compare them and finally you will see the commit https://github.com/elementary/greeter/commit/657ba9cdac18c21618b38d66d7e858a6adf9adc5 is not included in the version tag.

**Comment by jtrees** [comment]
This is still an issue.

**Comment by Blast-City** [comment]
> This is still an issue.

Tested on a new profile:

1- Logged in, closed onboarding, opened settings/power ,set suspend to 5min on battery and on power.
2- Checked /var/lib/AccountsService/users/my_user_name to see if the settings were saved.
3- Locked the screen and waited 5min.

**Result:** After 5 min the computer didn't suspend. After login it immediately suspended.

Am I doing anything wrong? 

P.S: I didn't test if disabling suspend works, but since setting suspend to 5min also doesn't work, probably after 30min the computer would suspend if it is on the lock/login screen.

**Comment by egonny** [comment]
To fix this previously (I wanted to disable suspend when connected to AC), I used the instructions given by https://github.com/elementary/switchboard-plug-power/issues/89 and applied

```dbus-launch gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type nothing```

as user `lightdm`. It seems something relating to this user has changed; after I changed this setting as `root` user, my suspend was disabled once again.

**Comment by jtrees** [comment]
Is this not going to be re-opened? Are the devs pretending this issue doesn't exist?

**Comment by gsupp** [comment]
> Is this not going to be re-opened? Are the devs pretending this issue doesn't exist?

Looks like this issue is now open under https://github.com/elementary/switchboard-plug-power/issues/139
