### ISSUE TITLE
Date format language not changing on login screen.

### ISSUE THREAD

**Issue by theJaxon** [elementary/greeter#171]
During setup the System detected my location and by default switched the date format to Arabic, i changed this in settings, however nothing changed on the login screen so when i log in the date is displayed in Arabic and the clock is in English, can't this be fixed ? 
Also i suggest that the mouse cursor by default be placed in the password text field because every time i boot the system i need to hover with my mouse and click on the password field.
Thanks.

**Comment by nikitati** [comment]
Confirmed, same issue with switching from Czech to English format. Greeter keeps region settings chosen during the installation, and ignores any changes to this setting.

**Comment by danrabbit** [comment]
Closing as a duplicate of #17
