### ISSUE TITLE
Power Setting not reflected to lightdm user

### ISSUE THREAD

**Issue by hezral** [elementary/greeter#176]
I've seen this reported on several places and also experience this on my laptop. This is on Juno. 
Suspend settings eventhough set to Never, still happens after the session is locked. 

This is one of the reported issues. There was also a workaround posted but i'm hoping this could be fixed for everyone. 

https://elementaryos.stackexchange.com/questions/16487/power-setting-doesnt-work

**Comment by cassidyjames** [comment]
Please search issues before filing new ones. This has been reported at https://github.com/elementary/greeter/issues/161. You can use the built-in GitHub reaction to :+1: it and mark it as affecting you, and comment if you have any additional useful information.

**Comment by hezral** [comment]
Sorry.. Thanks :)
