### ISSUE TITLE
No Wingpanel in LigthDM Greeter

### ISSUE THREAD

**Issue by 4ugustin** [elementary/greeter#178]
There's no more Wingpanel in LightDM Greeter.

Here's /var/log/lightdm/seat0-greeter.log which seems interessting:
https://hastebin.com/raw/yonaqareke

Another one here:
https://hastebin.com/raw/kiciyaliga

So these packages are causing the crash and are flatpak dependencies:

xdg-desktop-portal xdg-desktop-portal-gtk

```
$ sudo cat /var/log/lightdm/seat0-greeter.log | grep wingpanel
(wingpanel:13480): Gtk-CRITICAL **: 00:16:23.561: gtk_widget_set_no_show_all: assertion 'GTK_IS_WIDGET (widget)' failed
(wingpanel:13480): Gtk-CRITICAL **: 00:16:23.561: gtk_widget_show_all: assertion 'GTK_IS_WIDGET (widget)' failed
(wingpanel:13480): GLib-GObject-WARNING **: 00:16:23.564: invalid (NULL) pointer instance
(wingpanel:13480): GLib-GObject-CRITICAL **: 00:16:23.564: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(wingpanel:13480): GLib-GObject-WARNING **: 00:16:23.564: invalid (NULL) pointer instance
(wingpanel:13480): GLib-GObject-CRITICAL **: 00:16:23.564: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(wingpanel:13480): GLib-GObject-WARNING **: 00:16:46.175: invalid (NULL) pointer instance
(wingpanel:13480): GLib-GObject-CRITICAL **: 00:16:46.175: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
** (wingpanel:13480): CRITICAL **: 00:16:46.177: session_services_user_manager_update_all: assertion 'self != NULL' failed
```

**Comment by Nine-H** [comment]
I was about to report this. can you reboot your computer, note if the panel is displayed, and then lock it and note whether it was displayed again?

I only get the panel on first boot.

**Comment by 4ugustin** [comment]
No it's not displayed, but one time I woke up my system from suspendend state It was there, then after unlock Wingpanel instance crashed again.

**Comment by peteruithoven** [comment]
@4ugustin could you try honing in on what package specifically causes issue. Does the issue disappear when you remove those packages?

**Comment by 4ugustin** [comment]
@peteruithoven Nice I found them for first shot. Purged these dependencies of flatpak and It does work as is expected again without crash:

 libappstream-glib8 libgcab-1.0-0 libostree-1-1 xdg-desktop-portal xdg-desktop-portal-gtk

**Comment by 4ugustin** [comment]
@Nine-H Do you have flatpak installed?

**Comment by Nine-H** [comment]
I got an email about flatpak but it's not in the issue thread. Yeah, I have flatpak installed to pull down a couple of GNOME apps.

**Comment by 4ugustin** [comment]
@Nine-H I deleted it because I found that the issued Is caused by flatpak's dependencies as it's mentioned above so the workaround currently is remove these packages (and flatpak).

**Comment by 4ugustin** [comment]
I asked on #flatpak for help:

< mclasen> crmlt: thats a gtk bug. I thought this was fixed in 3.24.x. which version of gtk ?
< crmlt> mclasen: libgtk-3-0 3.22.30-1ubuntu1
< mclasen> I would suggest trying 3.24.1 and see if the issue goes away

**Comment by peteruithoven** [comment]
You could also try disabling individual indicators so see which one has an issue with flatpak. 
It looks like the individual indicators are installed to `/usr/lib/x86_64-linux-gnu/wingpanel` (assuming you're running a x86 64bit system). You could try renaming some of these from `*.so` to something like `*.backup`.

**Comment by 4ugustin** [comment]
@peteruithoven Tried disabling them one by one but found nothing.

**Comment by 4ugustin** [comment]
Still happens with compiled #181 
So probably it's really a gtk bug and thus will be unfixed until there will be libgtk 3.24.1 in ubuntu repos.

**Comment by worldofpeace** [comment]
@peteruithoven Any suggesting an any actions to take? 
I'm willing to help with debugging if time is permissible.

Also pinging @tintou

**Comment by peteruithoven** [comment]
It's weird that this would only happen in the greeter. 

It's started here: https://github.com/elementary/greeter/blob/master/src/Application.vala#L41
Would be great if we could get some more debug information from it, a bit like we normally can by running a process from the terminal with: `G_MESSAGES_DEBUG=all theprocess`
or using `gdb`. 

I've been able to get more debug info from Greeter with [some hacks](https://github.com/elementary/greeter/issues/144#issuecomment-432791326) in the past, but I really hope there is a better way. 
Normally logs seem to be accessible through `journalctl`, maybe there is a way to change the debug level on a per application basis.

**Comment by worldofpeace** [comment]
> It's weird that this would only happen in the greeter.
> 
> It's started here: https://github.com/elementary/greeter/blob/master/src/Application.vala#L41
> Would be great if we could get some more debug information from it, a bit like we normally can by running a process from the terminal with: `G_MESSAGES_DEBUG=all theprocess`
> or using `gdb`.
> 
> I've been able to get more debug info from Greeter with [some hacks](https://github.com/elementary/greeter/issues/144#issuecomment-432791326) in the past, but I really hope there is a better way.
> Normally logs seem to be accessible through `journalctl`, maybe there is a way to change the debug level on a per application basis.

Thanks for the tips. I'm willing to try anything at this point so lets see what this yields.

**Comment by janxkoci** [comment]
If I understand this issue correctly, at this moment I have a choice between wingpanel in greeter or my flatpak apps, as purging the two dependencies would break them, right?

**Comment by janxkoci** [comment]
I got some updates lately and today when unlocking the screen I noticed icons in the top right corner of my lock screen, just before I hit enter to confirm password. They were white on my light wallpaper (in session I have them black) but with a shadow, so quite visible. I tried to lock the screen again to try take a screenshot but they were gone :/ 

I locked the screen with keybord shortcut Super+L both times, however the first time after waking up the screen I had focus, while the second time (with icons missing) I didn't have focus, so it might be related to bug #144.

**Comment by jeremypw** [comment]
I found that the wingpanel appears after waiting 20 - 30 seconds.  Do you find this?  I am about to propose a PR to fix this.

**Comment by janxkoci** [comment]
Right now I mostly see it straight away (I was away for a week and returned few days ago, then installed updates), but I will watch out for this.

**Comment by jeremypw** [comment]
These race condition related issues often affect different systems differently.
