### ISSUE TITLE
Prompt Changes Which Monitor to Display On

### ISSUE THREAD

**Issue by seesemichaelj** [elementary/greeter#200]
The below issue is using the latest from `master` (as of https://github.com/elementary/greeter/commit/7928968844c2276cf521a4701e8c55915704abe1). I also have only tested via locking as I can't reboot currently, but will follow up when I have the chance sometime this weekend.

I have 4 monitors on a desktop machine. Every time I lock the screen, the monitor chosen to display the greeter toggles between the same two monitors. The two monitors are the first and last monitors displayed in the `xrandr` list.

**Comment by peteruithoven** [comment]
I don't understand what the "prompt" is in this case. But I think this would be solved if Greeter would follow the primary screen selected in the user settings, which is covered by: #65 so I'm closing this one.

**Comment by seesemichaelj** [comment]
The "prompt" in this case is the user login prompt. Basically, the monitor which the user login prompt was displayed on would change. I'm not sure if solving #65 is as feasible as it is to solve this issue.

However, I will defer to your judgment.
