### ISSUE TITLE
Remember/Predict the right user to show as default

### ISSUE THREAD

**Issue by danrabbit** [elementary/greeter#204]
Right now it seems like I always see the last added user selected. At the minimum we should remember and show the last logged in user. But if we were really smart and awesome, we would do some ~Machine Learning™~ basic statistics to see who is most likely to be logging in at the given datetime/place and show that card as default

**Comment by cassidyjames** [comment]
I think unless it was _perfect_ (which is impossible), attempting to predict the user would come off as unpredictable/buggy. A much simpler and consistent scenario of last-logged-in seems to be reliable and good enough without seeming like unpredictable.

**Comment by vjr** [comment]
With the release of the new greeter the last logged in user is not presented for login by default. It shows the first user in the alphabetical list of a few users that I have created.

It was working on my local build prior to the release (when I submitted some patches to master) so not sure what is causing the issue now.

**Comment by cassidyjames** [comment]
This is a regression since the previous greeter remembered the last-logged-in user.
