### ISSUE TITLE
Change Light-Locker to something else

### ISSUE THREAD

**Issue by otavioschwanck** [elementary/greeter#207]
Light locker is the only one that have problems.  Black screen when back from lock, no sound when blocked, internet down when blocked.  

Would be nice change it to gnome-screensaver with a nice theme or the xscreensaver, maybe.

**Comment by Blast-City** [comment]
Hi.

Another thing that i don't remember happening in Ubuntu Unity is the disk access that happens every time you lock the screen.

Sometimes i also see the screen appear for a brief moment after pressing Super+l and the screen being black for some seconds.

**Comment by francesco-taioli** [comment]
same isse here. when i click `super + l` it take too long ( a couple of second ) before go to lock

**Comment by danrabbit** [comment]
I'm going to close this issue report since it describes several issues. Can you instead open separate issue reports for each encountered problem?
