### ISSUE TITLE
Greeter does not follow user settings

### ISSUE THREAD

**Issue by ethanay** [elementary/greeter#211]
Not sure if this is related to other greeter issues (e.g., https://github.com/elementary/greeter/issues/161) but I am left-handed and set up my pointing device for main click on the right button, secondary click (e.g., context menu) on left button. However, on the lock screen to lock back in to the desktop, the pointing device reverts back to right handed default (main click left, secondary click right). I have also disabled tap to click, but it remains in the Greeter

**Comment by valkirilov** [comment]
+1

The settings are ignored at all. I am using a personal preferences for a 24 hours time format, but the Greeter still uses AM/PM.

**Comment by jsparknz** [comment]
I also use 24 hour time format. It bugs me that the logon and lock screens don't reflect this.

**Comment by vadbars** [comment]
Yes, localized time in Russian is shown as 12:23 П.П. instead 12:23

**Comment by peteruithoven** [comment]
There is an open issue on mouse settings: #70
In regards to time format please retest this with the latest, unreleased, version.
