### ISSUE TITLE
Greeter does not respect screen rotation settings on login screen

### ISSUE THREAD

**Issue by colinkiama** [elementary/greeter#216]
The laptop being used has an accelerometer. Because of this, I lock the screen orientation. 

Sometimes, when opening the lid, the login screen appears upside down. After logging in, the display orientation goes back to normal.

Here's a picture of the problem:

![wp_20181126_23_44_11_pro_li](https://user-images.githubusercontent.com/16501024/49050380-10653480-f1db-11e8-9e55-4d961850f982.jpg)

Expected result: Login screen should always appear right-side up.

**Comment by arshubham** [comment]
This is a common problem with HP laptops. For now you can run the following commands to mitigate this.

`sudo su`
`su - -s /bin/bash lightdm`
`dbus-launch gsettings set org.gnome.settings-daemon.peripherals.touchscreen orientation-lock true`

You only need to run this once after installation.

**Comment by peteruithoven** [comment]
@arshubham This should be editable using the Display settings (On laptops without touchscreens the option is currently not shown see: https://github.com/elementary/switchboard-plug-display/issues/116), or is the issue that this setting isn't applied to the Greeter / login screen?

**Comment by arshubham** [comment]
@peteruithoven Screen Rotation in display setting is None on my laptop, however without setting this gsetting the screen still rotates. This is a bug in some HP laptops. I can set orientation-lock to true for a user but the settings are not applied to greeter. In Gnome Rotation Lock is the option in the panel popover in both session and GDM.

**Comment by peteruithoven** [comment]
I find it hard to believe it's a HP specific issue. Especially since the solution is to set this  setting for the `lightdm` user?

I think there are 2 solutions:
1. Have the setting also apply to this user in the System settings.
2. Also have a way to set this from the Greeter.
