### ISSUE TITLE
Crash when switching to lockscreen

### ISSUE THREAD

**Issue by ZaycevNet** [elementary/greeter#221]
Elementary OS Jino x64
Intel® Core™ i5-4210U
Intel Corporation Haswell-ULT Integrated Graphics Controller
NVIDIA Corporation GF117M [GeForce 610M/710M/810M/**820M** / GT 620M/625M/630M/720M]
RAM 8gb

After logging in, if you select “**lock screen**” on the shutdown icon, the monitor simply starts blinking and stops responding to any actions.

Write to the mail(alex.grebenikov@yandex.by) and I will send you the necessary information and screenshots

**Comment by peteruithoven** [comment]
There is not enough information to go on in this issue. There also have been no thumbs up. 
@ZaycevNet could you try again with the latest, unreleased, version of the greeter from github? 
For now I'm closing this issue.
