### ISSUE TITLE
Hide disabled user accounts

### ISSUE THREAD

**Issue by cassidyjames** [elementary/greeter#236]
If a user account is disabled in System Settings → User Accounts, it should not show up on the greeter.

**Comment by danrabbit** [comment]
Hm, are we sure not showing the account is the right thing to do instead of making it insensitive in some way? I guess there's a question of what the use case is for disabling instead of removing

**Comment by cassidyjames** [comment]
Yeah I suppose marking as insensitive (and sorting to the end?) could work well and would better reflect that the account exists, but is not enabled. Disabling a user account could be good for only enabling an account when someone is visiting, like I do with my extended family. I don't remove it so that their files are still there, but it's also not cluttering up the greeter, and it reduces any sort of attack vector (those users could be using a potentially-less secure password). 

Is disabling an account also what the Parental Controls does outside of the "allowed" hours?

**Comment by danrabbit** [comment]
@donadigo ? ^

**Comment by cassidyjames** [comment]
@danrabbit I recall it's done in PAM, so I don't think it literally disables the account. This was also filed as part of the Parental Controls hackfest, if it helps: https://github.com/systemd/systemd/issues/12035

**Comment by ibrahimrahman** [comment]
The libvert-qemu user shows up as disabled in the new greeter. I'm using the .deb linked in Daniel Foré's Reddit post (3.3.1+r773+pkg61). While making regular disabled user accounts insensitive makes sense, shouldn't this user be removed from the greeter altogether instead of  being disabled?

**Comment by danrabbit** [comment]
@ibrahimrahman Can you raise a new issue about this? It sounds like this user should not be shown on the greeter, but this seems like a different issue

**Comment by ibrahimrahman** [comment]
Done

**Comment by danrabbit** [comment]
ty!
