### ISSUE TITLE
hard-code GTK and icon theme used by the greeter 

### ISSUE THREAD

**Issue by decathorpe** [elementary/greeter#239]
On systems where the default GTK and icon theme can't be overridden system-wide (e.g. on fedora, and most non-elementaryOS distributions), the greeter has visual issues.

I think in this case, where the program really is explicitly dependent on specific GTK styles from the elementary GTK stylesheet and on specific icons from the elementary icon theme, it would be appropriate to disregard the system settings and hard-code the themes instead, to fix potential issues.

**Comment by worldofpeace** [comment]
:+1:  for sure, this would allow us in NixOS to drop some hacks to ensure that this theme is always used.

**Comment by decathorpe** [comment]
I'm wondering whether something like this could be done for wingpanel as well?

It could detect whether it's running in the greeter session, and then force the `elementary` themes. On the other hand, it wouldn't hurt to always hard-code the themes used by wingpanel anyway, since almost all other GTK/icon themes look broken
