### ISSUE TITLE
Resize jump

### ISSUE THREAD

**Issue by peteruithoven** [elementary/greeter#245]
I've got a HiDPI screen and I noticed that in a lot of cases the Greeter seems to start out smaller and then resizes to a normal size:
![VID_20190315_201448~2 mp4](https://user-images.githubusercontent.com/523210/54457371-7ad9ba80-4761-11e9-9896-d13f7de9fb6b.gif)

It might be related to: #144 as when I see this jump happen the field won't be focused. Even after: https://github.com/elementary/greeter/pull/243

**Comment by danrabbit** [comment]
I think this is because we render the greeter before GSD is loaded. I wonder if it would be better to try to remember the last setting and load that in a way that is faster than waiting for GSD or if we should wait to render the greeter until after GSD is loaded
