### ISSUE TITLE
tty1 login screen is shown for a moment in between elementary's splash screen and the greeter.

### ISSUE THREAD

**Issue by Blast-City** [elementary/greeter#254]
**elementary OS Juno fully updated:**

1- Start the computer.
**Result:** After the elementary "e" splash screen the tt1 login screen is shown for two or three seconds before the login/greeter screen.

This didn't happen on Loki.

PS: Sorry if this isn't the right place to report this issue.

**Comment by Blast-City** [comment]
It's not my video, but it shows the issue at 25s:

[Link](https://www.reddit.com/r/elementaryos/comments/b4xf31/please_help_me_with_the_boot_delay/)

**Comment by ReductoAdAbsurdum** [comment]
(From ARCH's wiki: silent boot article):
agetty
To hide agetty printed issue and "login:" prompt line from the console[3], create a drop-in snippet for getty@tty1.service.

/etc/systemd/system/getty@tty1.service.d/skip-prompt.conf
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --skip-login --nonewline --noissue --autologin username --noclear %I $TERM

**Comment by Blast-City** [comment]
Thanks.

I will close this issue because I asked in Linuxquestions if anyone was having an issue where, unlike othere tty's, tty1 font is bold and someone was also getting this problem on Ubuntu with Lightdm.
