### ISSUE TITLE
Setting specific wallpaper

### ISSUE THREAD

**Issue by kepicorp** [elementary/greeter#257]
The parameter exist but is not taken into account:
[greeter]
#activate-numlock=true
default-wallpaper=/usr/share/backgrounds/lock.jpg
#high-contrast=false
#onscreen-keyboard=false
#screensaver-timeout=60

**Comment by danrabbit** [comment]
Closing as a duplicate of https://github.com/elementary/switchboard-plug-pantheon-shell/issues/28
