### ISSUE TITLE
Locking the screen doesn't always turn off the monitor. Automatic cursor position causing it?

### ISSUE THREAD

**Issue by Blast-City** [elementary/greeter#261]
1- Lock screen or wait X seconds (power option).
**Result:** The monitor turns off, but when the mouse cursor moves to bottom right of the screen the monitor turns on again.

I think that Juno's new feature that moves the mouse to the bottom right of the screen is sometimes causing the monitor to turn on again.

Elementary OS Juno fully updated. New user profile.

**Comment by peteruithoven** [comment]
> Juno's new feature that moves the mouse to the bottom right of the screen

You're referring to #162?

**Comment by Blast-City** [comment]
> > Juno's new feature that moves the mouse to the bottom right of the screen
> 
> You're referring to #162?

Hi.

Yes. I thought it was a Juno new feature, but apparently it's not.

**Comment by Blast-City** [comment]
Duplicate of #155.
