### ISSUE TITLE
Unnecessary AM/PM labels for 24H format

### ISSUE THREAD

**Issue by romdef** [elementary/greeter#270]
This issue #225 was previously closed after a submitted fix but still persist.
I don't know how it is hard to fix, and it's ridiculous (not important) thing, but it's not elegant for new users (and first hours fans) who is experiencing your fantastic efforts with elementary ! ;-)

**Comment by peteruithoven** [comment]
Seeing that it's closed, are you sure you've tested this with the latest `master` version? Because this latest version hasn't been released yet.

**Comment by romdef** [comment]
I'm using Juno stable (public) version with last updates from APT / AppCenter.
![IMG_20190416_155450](https://user-images.githubusercontent.com/183035/56216115-2166f300-6061-11e9-9cb5-98194e3aa16c.jpg)

**Comment by peteruithoven** [comment]
That means you're not running the unreleased latest version of the Greeter that exists in this repository. 
To try this version you can follow:
https://github.com/elementary/greeter#building-and-installation

To return to the original version see: https://elementary.io/docs/code/os-dev > Restoring original packages

I'm closing this issue for now, if you've seen the issue persists in the latest version of the code please reopen the issue. 

I understand this is confusing, but it makes managing issues (all the work still needs to be done) a lot easier.
