### ISSUE TITLE
Greeter shows Initial Setup on the Installer session

### ISSUE THREAD

**Issue by ryonakano** [elementary/greeter#273]
## Expected Behavior

Greeter should not show Initial Setup in the Installer session, and if the screen is locked it should provide a way for users to come back to the Installer. Or, the screen is not locked in the Installer session.

## Actual Behavior & Steps to Reproduce the Behavior

- Boot your machine from daily iso
- After a while the new Installer is shown
- Just wait without touching a keyboard, mouse, etc. After a couple of minutes the computer is locked, turns to black screen, and Greeter is shown with Initial Setup
- You can create a new user with Initial Setup but after creating a user Greeter says that account is disabled, and you can no longer back to Installer unless you reboot your machine

Here is a video which I took:

https://youtu.be/wfoW8p5Xcc8

**Comment by danrabbit** [comment]
This seems to be fixed! In the daily ISO I can confirm that eventually the screen does turn off (it took me a LONG time). But upon waking the computer, I'm still in the installer session. No lock screen with initial setup :)
