### ISSUE TITLE
Can't build from source: Dependency "accountsservice" not found

### ISSUE THREAD

**Issue by MadByteDE** [elementary/greeter#274]
[meson-log.txt](https://github.com/elementary/greeter/files/3154238/meson-log.txt)

I'm running vanilla Elementary OS 5.0 (64bit).

Not sure what the problem is but after searching forever in forums and the issues tab, I couldn't find a solution for the problem.

When I try to build the repo I get the following terminal output:
![Screenshot von 2019-05-07 21 34 44](https://user-images.githubusercontent.com/4752038/57327754-f7f53080-710f-11e9-84aa-c103b7d4a93d.png)

btw.. I'm trying this to see if the "AM/PM" translation bug is fixed (German translation "Vormittags(AM) / Nachmittags(PM)" displayed which causes the layout to break) in the newest version of the greeter, because this is one of a few things that's really annoying with the OS.

![IMG_20190507_214413](https://user-images.githubusercontent.com/4752038/57328395-9df56a80-7111-11e9-88ac-67c6ff560b59.jpg)

**Comment by donadigo** [comment]
You have to install the dependencies greeter requires to build itself. Try doing `sudo apt build-dep pantheon-greeter` first and then do all the build instructions. Closing.

**Comment by MadByteDE** [comment]
First: Does not work!
Second: Should be stated in the instructions (if it would work)
Third: Closing after 1min without reading the post / considering to investigate the second bug is kinda rude in my opinion and not helpful.

**Comment by cassidyjames** [comment]
@MadByteDE usually dependencies are pulled in with that command (and listed in the README), but that dependency was recently added to master. I've updated the README. You just need to install `libaccountsservice-dev`.
