### ISSUE TITLE
Greeter does not respect time format settings

### ISSUE THREAD

**Issue by MadByteDE** [elementary/greeter#275]
The problem with the old greeter version was that the 24h format had AM/PM labels and in the german translation also was misaligned because of bad/too long translations.

The new version now completely ignores system preferences and displays a 12h format time.

![comparison](https://user-images.githubusercontent.com/4752038/57390645-24b35180-71bd-11e9-8ed4-f52b7f7edb64.jpg)

OS: Elementary OS 5.0
Screen Res: 1920x1080
Greeter version: Latest master (8th May 2019).

**Comment by peteruithoven** [comment]
There is a more general issue that the Greeter doesn't follow settings: https://github.com/elementary/greeter/issues?utf8=%E2%9C%93&q=user+settings+is%3Aopen+is%3Aissue+
It's challenging because there can be multiple users each having their own settings.

**Comment by danrabbit** [comment]
This is fixed within the scope of the greeter repo. There is another branch out against the Date & Time settings plugin for Switchboard that will need to be merged for the issue to be resolved completely, but as far as Greeter is concerned the issue is fixed here.
