### ISSUE TITLE
create-symlink script broken

### ISSUE THREAD

**Issue by decathorpe** [elementary/greeter#287]
```
Running custom install script '/builddir/build/BUILD/elementary-greeter-3.3.1+git190528.120045.bed3ea45/data/create-symlink.py share/dbus-1/interfaces/io.elementary.greeter.AccountsService.xml share/accountsservice/interfaces/io.elementary.greeter.AccountsService.xml'
Failed to run install script '/builddir/build/BUILD/elementary-greeter-3.3.1+git190528.120045.bed3ea45/data/create-symlink.py share/dbus-1/interfaces/io.elementary.greeter.AccountsService.xml share/accountsservice/interfaces/io.elementary.greeter.AccountsService.xml'
```

It looks like it doesn't calculate the destination correctly, since the prefix is missing.

**Comment by decathorpe** [comment]
Also, the scipt uses python3's `print` syntax, but uses the python2 shebang ...

**Comment by worldofpeace** [comment]
Has
* https://github.com/elementary/greeter/commit/25da6767e0c5224741345682e5403a60e61b992f
* https://github.com/elementary/greeter/commit/665d2114cf2d204417d48fb9cb672791f395bd9c

fixed this for you?

**Comment by decathorpe** [comment]
Seems like it. Thanks for following up on this
