### ISSUE TITLE
Greeter jumps in scale and password input loses focus

### ISSUE THREAD

**Issue by joedborg** [elementary/greeter#292]
Maybe related to https://github.com/elementary/greeter/issues/160.  I'm on a Dell XPS 13 9730 (13" QHD/4K).  When the Greeter shows on boot, the scale appears to be 1x with the focus clearly in the password input (the cursor blinks).  After a second it scales to 2x and loses focus, which you can't bring back with tab, or return (you have to click).

**Comment by peteruithoven** [comment]
This has been fixed in the latest Greeter, it hasn't been released yet though. 

https://github.com/elementary/greeter/pull/247
https://github.com/elementary/greeter/issues/245

**Comment by joedborg** [comment]
Thanks @peteruithoven
