### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yelloball** [elementary/greeter#297]
I get a dependency error while installing the package. I have done `sudo apt install -f` as well.

![greeter-installation-error](https://user-images.githubusercontent.com/14001336/60315685-36c39c00-9985-11e9-873e-b53319db5d34.png)

**Comment by cassidyjames** [comment]
I believe you also need granite from the daily PPA.

**Comment by danrabbit** [comment]
Yes, you'll want the granite packages from here:

https://launchpad.net/~elementary-os/+archive/ubuntu/daily/+build/16509105
