### ISSUE TITLE
Shows some parts English although language is not an English.

### ISSUE THREAD

**Issue by bagjunggyu** [elementary/greeter#30]
In case of "locale - USA, language -ko", Greeter shows some part English, although other components of system shows correctly Korean.
![greeter](https://cloud.githubusercontent.com/assets/2834031/25566908/0361dea0-2e1e-11e7-95cd-f9646aed9ef2.JPG)

**Comment by stsdc** [comment]
Affects me too. Moreover, I have turned 24-hour format, but greeter still shows AM/PM.
