### ISSUE TITLE
Allow user to set orientation preference.

### ISSUE THREAD

**Issue by cccccccarter** [elementary/greeter#305]
This falls strictly into the wishlist category but, it would be nice to see an option added for users to be able to set a preference for horizontal or vertically scrolling user cards/panels instead of being limited to solely horizontally scrolling cards/panels.

**Comment by peteruithoven** [comment]
elementary OS always tries to limit the amount of options, limiting the amount of complexity and making sure we can focus on the behaivior that's used. So I don't think this will happen.
