### ISSUE TITLE
Wrong time displayed after suspend

### ISSUE THREAD

**Issue by JeanChristopheGuerin** [elementary/greeter#306]
Using the new greeter (from pantheon-greeter_3.3.1+r773+pkg61~daily~ubuntu5.0.1_amd64.deb).

Sometimes, when waking the computer after a suspension the time displayed on the greeter isn't the current time but the time it was when the machine was suspended.

EDIT: 
It is reproductible every time the system is suspended. It doesn't when it is locked.

Tested on a Huawei matebook D (AMD Ryzen 2500U)
Power settings: 
Shut down screen after 30 min
Shutdown button: suspend
Laptop screen closed: lock
Laptop screen closed with external monitor: lock
(sorry these aren't the exact labels, my system isn't in english)

elementary OS 5.0 Juno
Linux 4.15.0-54-generic
Gtk+ 3.22.30

**Comment by cassidyjames** [comment]
@JeanChristopheGuerin does the time snap back to the correct time after a moment, or does it stay incorrect? Is the rest of the greeter still operable?

**Comment by JeanChristopheGuerin** [comment]
The greeter is fully operable.
The time stays incorrect until trying to log in. It corrects itself when validating whether the password is correct or not.

I'll try to add a short video.

I was incorrect in my first post, it happens every time the system is suspended and never when it's only locked.
