### ISSUE TITLE
The return of the Dynamic user

### ISSUE THREAD

**Issue by peteruithoven** [elementary/greeter#316]
Suddenly I'm seeing the Dynamic user again. This happened in the new Greeter, but I've been using the new Greeter for quite a while, so I'm not sure what triggered the change. 

![IMG_20190723_205510](https://user-images.githubusercontent.com/523210/61745525-06132e80-ad9a-11e9-9f7f-a3f4ce4e9853.jpg)
![Screenshot from 2019-07-23 22-38-06@2x](https://user-images.githubusercontent.com/523210/61745789-93568300-ad9a-11e9-8e39-00a6a3b944c7.png)

As you can see my User Accounts settings mentions "systemd-timesync" under the Dynamic user (just like last time).

Contents of `/etc/lightdm/users.conf`:
```
[UserList]
minimum-uid=500
hidden-users=nobody nobody4 noaccess
hidden-shells=/bin/false /usr/sbin/nologin
```

Previous issue on the Dynamic user: https://github.com/elementary/greeter/issues/157

**Comment by kp2401075** [comment]
Having same issue as well.

**Comment by danrabbit** [comment]
Closing because this turns out to be an upstream bug and should be resolved in future versions of Ubuntu: https://github.com/elementary/greeter/issues/328#issuecomment-528019539
