### ISSUE TITLE
Non-16:9 wallpapers glitch the user card in new Greeter

### ISSUE THREAD

**Issue by lainsce** [elementary/greeter#325]
Any non-16:9 wallpaper will have this glitched top half happen:
![photo_2019-08-24_13-05-22](https://user-images.githubusercontent.com/4886639/63639919-1efc5180-c670-11e9-870a-d982e21f4556.jpg)

Test the greeter with a wallpaper of any of these resolutions (confirmed glitching by me):
- 2560×1080
- 1280×1280

**Comment by mderrien29** [comment]
21:9 @ 2560x1080 

No issues for me.

**Comment by jlnr** [comment]
Also ~21:9 (on a matching screen), no issues.

**Comment by meisenzahl** [comment]
Same issue for me with 3440 x 1440:

http://i.imgur.com/5Sw5ZtG.png

**Comment by cassidyjames** [comment]
@lainsce what image format and file size are you dealing with? Are you on Intel, AMD, or NVIDIA?

**Comment by cassidyjames** [comment]
@meisenzahl are you on Intel AMD, or NVIDIA?

**Comment by meisenzahl** [comment]
> @meisenzahl are you on Intel AMD, or NVIDIA?

I have the issue on Intel Pentium N4200.

**Comment by lainsce** [comment]
I'm on AMD, and my image is a custom black & white image made from a coloured wallpaper found online.

**Comment by janxkoci** [comment]
My wallpaper isn't 16:9 (1280 x 853) but I don't see this issue. It's this [file](https://www.dropbox.com/s/rj4uumruru7ptab/tumblr_ng02mlVAET1tc258so5_r1_1280.png?dl=0).

**Comment by danrabbit** [comment]
I can reproduce the issue on Intel with the background from https://github.com/elementary/greeter/issues/325#issuecomment-526167130

**Comment by cassidyjames** [comment]
If I recall, there's a max texture size, and that's smaller for Intel cards. Could be that we need to downscale the wallpaper before drawing it? I'm not sure exactly.

**Comment by lainsce** [comment]
That shouldn't be a problem in 2005 hardware up to today's hardware.

AFAIK it's 16384x16384 the max size since then.
