### ISSUE TITLE
Password entry becomes insensitive

### ISSUE THREAD

**Issue by samermi1** [elementary/greeter#333]
I lock my system more than 10 times a day and I have had the problem two times since Tuesday. When I tried to unlock the system I couldn't get the password field focused neither with the mouse nor with the keyboard. I have a video of the situation I will post it later.

**Comment by samermi1** [comment]
The clicking sounds are not included 🙂
![ezgif-1-563f0f4b2929](https://user-images.githubusercontent.com/31795877/63921560-50479980-ca43-11e9-8f57-85eab62d5773.gif)

**Comment by samermi1** [comment]
I can regenerate the issue by pressing Enter with an empty password

**Comment by danrabbit** [comment]
@samermi1 Are you saying that any time you lock the screen you can reproduce this by hitting enter without typing your password?

Can you try building [this branch](https://github.com/elementary/greeter/pull/335) and seeing if that either resolves the issue or at least gives you an error dialog?

**Comment by samermi1** [comment]
@danrabbit Yes that is exactly what happens. 
I have built the branch and ran lightdm in debugging mode it logged the following to /home/.cach/lightdm/log/lightdm.log:
`[+0.00s] DEBUG: Logging to /home/samer/.cache/lightdm/log/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.26.0, UID=1000 PID=6545
[+0.00s] DEBUG: Loading configuration dirs from /var/lib/snapd/desktop/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/40-io.elementary.greeter.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-disable-guest.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-disable-log-backup.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-greeter-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-guest-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-xserver-command.conf
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /var/lib/flatpak/exports/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /home/samer/.local/share/flatpak/exports/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/pantheon/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/gnome/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/xdg-pantheon/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Running in user mode
[+0.00s] DEBUG: Using Xephyr for X servers
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Registered seat module unity
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: Monitoring logind for seats
[+0.00s] DEBUG: New seat added from logind: seat0
[+0.00s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.00s] DEBUG: Seat seat0: Starting
[+0.00s] DEBUG: Seat seat0: Creating greeter session
[+0.01s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.01s] DEBUG: User /org/freedesktop/Accounts/User1000 added
[+0.01s] DEBUG: User /org/freedesktop/Accounts/User1001 added
[+0.01s] DEBUG: Seat seat0: Creating display server of type x
[+0.01s] DEBUG: Seat seat0: Starting local X display
[+0.01s] DEBUG: XServer 1: Logging to /home/samer/.cache/lightdm/log/x-1.log
[+0.01s] DEBUG: XServer 1: Writing X server authority to /home/samer/.cache/lightdm/run/root/:1
[+0.02s] DEBUG: XServer 1: Launching X Server
[+0.02s] DEBUG: Launching process 6606: /usr/bin/Xephyr :1 -seat seat0 -auth /home/samer/.cache/lightdm/run/root/:1 -nolisten tcp
[+0.02s] DEBUG: XServer 1: Waiting for ready signal from X server :1
[+0.02s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.02s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.12s] DEBUG: Process 6606 terminated with signal 11
[+0.12s] DEBUG: XServer 1: X server stopped
[+0.12s] DEBUG: XServer 1: Removing X server authority /home/samer/.cache/lightdm/run/root/:1
[+0.12s] DEBUG: Seat seat0: Display server stopped
[+0.12s] DEBUG: Seat seat0: Stopping session
[+0.12s] DEBUG: Seat seat0: Session stopped
[+0.12s] DEBUG: Seat seat0: Stopping display server, no sessions require it
[+0.12s] DEBUG: Seat seat0: Stopping; greeter display server failed to start
[+0.12s] DEBUG: Seat seat0: Stopping
[+0.12s] DEBUG: Seat seat0: Stopped
[+0.12s] DEBUG: Required seat has stopped
[+0.12s] DEBUG: Stopping display manager
[+0.12s] DEBUG: Display manager stopped
[+0.12s] DEBUG: Stopping daemon
[+0.12s] DEBUG: Exiting with return value 1`


I have logged out and tried with no password to log in, as usual I couldn't. Then after restarting the computer, there was nothing new in the lightdm logs. But the following lines are from the syslog:

`Aug 30 08:48:06 samer-pc dbus-daemon[894]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.108' (uid=110 pid=7627 comm="/usr/lib/gnome-settings-daemon/gsd-media-keys " label="unconfined")
Aug 30 08:48:06 samer-pc systemd[1]: Starting Hostname Service...
Aug 30 08:48:06 samer-pc dbus-daemon[894]: [system] Successfully activated service 'org.freedesktop.hostname1'
Aug 30 08:48:06 samer-pc systemd[1]: Started Hostname Service.
Aug 30 08:48:31 samer-pc pulseaudio[7660]: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
Aug 30 08:48:31 samer-pc gsd-color[1829]: failed to set screen _ICC_PROFILE: Failed to open file “/var/lib/lightdm/.local/share/icc/edid-e8a54619b73eccde165bb153394c43c9.icc”: Permission denied
Aug 30 08:48:53 samer-pc systemd[1]: Starting Cleanup of Temporary Directories...
Aug 30 08:48:53 samer-pc systemd[1]: Started Cleanup of Temporary Directories.
Aug 30 08:48:56 samer-pc gsd-color[1829]: failed to set screen _ICC_PROFILE: Failed to open file “/var/lib/lightdm/.local/share/icc/edid-e8a54619b73eccde165bb153394c43c9.icc”: Permission denied
`

If there is anyway I can help, I will be my pleasure.

**Comment by danrabbit** [comment]
@samermi1 Just to be clear, did you install the branch and confirm that you can still reproduce the issue with that branch installed? And with that branch you don't see any error dialog (not logs, but an actual new window)?

**Comment by samermi1** [comment]
Yes, I can confirm that

**Comment by KarkanAlzwayed** [comment]
I am having a similar issue. It doesn't happen a lot. Every now and then after I lift the lid, the keyboard pretty much useless. I'd type my password but nothing is being typed. The cursor moves, but the password field doesn't take the password. A reboot fixes it for me.
