### ISSUE TITLE
New greeter animation of background is weird

### ISSUE THREAD

**Issue by janxkoci** [elementary/greeter#342]
On slower hardware (e.g. Intel Celeron N3050) the greeter after e.g. locking screen shows weird "animation". The backgroun is first black with the user widgets, and after those are loaded the background switches from black to dark grey.

I assume the goal was to not show black and instead have dark grey directly. Maybe on macbooks the transition is fast enough to not be noticed, but on my netbook it looks weird.

**Comment by worldofpeace** [comment]
I ran reproduce this issue with a machine with a much newer processor than a Intel Celeron N3050.
I first noticed it after https://github.com/elementary/greeter/commit/f9593b5c1f6828edc9841d022dae1dc16e594c8d, so perhaps it needs to be confirmed if there's a regression from this.

**Comment by janxkoci** [comment]
If that's the commit that was supposed to fix the greeter flickering with certain wallpapers, then I don't think it caused this as I seen it from the beginning (after the new greeter arrived via update).
