### ISSUE TITLE
Brightness keys breaks the system.

### ISSUE THREAD

**Issue by osmarvjr** [elementary/greeter#344]
In labtop when using the brightness keys, fn + brightness key the system breaks, and the brightness status is fixed at the top corner of the screen.

**Comment by janxkoci** [comment]
Brightness keys did nothing for me in the old greeter but work as expected in the new redesigned version. Can you still reproduce the issue?

**Comment by osmarvjr** [comment]
> Brightness keys did nothing for me in the old greeter but work as expected in the new redesigned version (introduced in October). Can you still reproduce the issue?

I opened in the wrong session, sorry.
The problem happens when I'm on the desktop.

Google translater english, sorry =)
