### ISSUE TITLE
freeze after lock screen

### ISSUE THREAD

**Issue by rizkyramadhanch** [elementary/greeter#348]
for a moment a lock my elementary os, then i try to relogin, it can't type anything on my user account, also i can't use my fingerprint to login.

please help me
thank you so much :*

**Comment by pmop** [comment]
Can confirm. I'll be bringing the logs soon.

**Comment by pmop** [comment]
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1788018 seems to be the culprit here, at least for me.

**Comment by pmop** [comment]
Isn't this issue dupe with #198 and #78?

**Comment by kgrubb** [comment]
duplicate of #78
