### ISSUE TITLE
Size cards relative to the display

### ISSUE THREAD

**Issue by cassidyjames** [elementary/greeter#353]
On larger/higher res displays, we could make the user cards bigger. Especially like 27" 1440p displays.

**Comment by jlnr** [comment]
This is a duplicate of #303, I'll close my ticket.

**Comment by cassidyjames** [comment]
@jlnr ah derp, I should have remembered that issue. For issue tracker etiquette I'll actually close this as a dupe since yours was filed first. :sweat_smile:
