### ISSUE TITLE
Using a custom wallpaper doesn't change the preview in Greeter

### ISSUE THREAD

**Issue by 413Michele** [elementary/greeter#354]
Possibly related to https://github.com/elementary/greeter/issues/309

Steps to reproduce:
1. Open a picture
2. Set it as wallpaper from the image viewer
3. The preview in Greeter is the default wallpaper

As another test, I changed the wallpaper to a default one and then to the custom one again from Switchboard: the preview worked with the default one and not with the custom one

**Comment by cassidyjames** [comment]
I can't reproduce this; following the steps for me successfully sets the wallpaper, and locking or logging out shows the correct wallpaper on the greeter.

**Comment by worldofpeace** [comment]
Can you look at https://github.com/elementary/switchboard-plug-pantheon-shell/issues/181 and inspect the permissions of the files mentioned there? That's the only reason I can think of that it wouldn't appear.

**Comment by 413Michele** [comment]
Ok, I inspected `/var/lib/lightdm-data/$user/wallpaper/$background` and you're right, it was 400.
Setting the permission to 404 solves the issue, switching to another WP and then switching back causes it again (I think it inherits the permissions fro the original files).

**Comment by 413Michele** [comment]
Update: now it works with every picture I download, I set them from the image viewer and I can see them it in Greeter. Maybe the update from today changed something?

**Comment by worldofpeace** [comment]
> Update: now it works with every picture I download

Are the permissions of the files you've downloaded correct? I guess we've already established that it didn't work for you when the permissions were 400.

**Comment by 413Michele** [comment]
Yeah, but it was 400 for `$background` only, the downloaded file was 664 I think. I can make some tests by changing the permissions in the original file, before setting it as WP

**Comment by 413Michele** [comment]
I got it, this reproduces the problem:

1. Open Unsplash (on Firefox)
2. Click **Download free**
3. When Firefox prompts it, choose **Open With - Photo Viewer** (this opens the pic as a temp file)
4. Right Click -> Set as wallpaper
5. No preview on Greeter

This because the temp file is saved in `/tmp/mozilla_user0/`, with 400 permission.

At this point I don't know if it's even worth to fix it, as it's a very rare case. Should I open an issue in Photos?

**Comment by worldofpeace** [comment]
The issue I opened at https://github.com/elementary/switchboard-plug-pantheon-shell/issues/181 is where the issue can be fixed. 

> Set the wallpaper with the "Set as Desktop Background" contract or within switchboard

By selecting "Set as wallpaper" you interact with the contract in `switchboard-plug-pantheon-shell`.
I believe an good solution would be:
> Within switchboard-plug-pantheon-shell ensure the correct permissions for the copy of the background for the greeter.

> This because the temp file is saved in /tmp/mozilla_user0/, with 400 permission.
> At this point I don't know if it's even worth to fix it, as it's a very rare case. 

That's actually a very common case, there's many users of firefox.

**Comment by davidmhewitt** [comment]
The issue tracked in the switchboard plug has now been fixed and this fix will be pushed out to users during the next update to the switchboard plug. Any wallpapers with restrictive permissions will have new permissions applied for the copy in the greeter data directory, so that it is able to be read and displayed.
