### ISSUE TITLE
Blurred Greeter does not apply when install

### ISSUE THREAD

**Issue by CrisThunder** [elementary/greeter#363]
I tried to install the Blurred Greeter by Source Code, but when I run `sudo ninja install` it won't apply to the login screen.
There is no error or missing dependencies.

Here are my specs:
`Linux Cris-Zenbook 5.3.1-050301-generic #201909210632 SMP Sat Sep 21 06:34:27 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
`Elementary 5.0 Juno`.

**Comment by danrabbit** [comment]
The blur branch has not been merged into master.

Closing because this issue report is about an experimental branch and not a release or master
