### ISSUE TITLE
Dual screen wallpaper problem (3840x1080)

### ISSUE THREAD

**Issue by rklepacz** [elementary/greeter#373]
My desktop wallpaper (3840x1080)
![Zrzut ekranu z 2019-10-28 21-53-43](https://user-images.githubusercontent.com/52511856/67719123-823c9400-f9d1-11e9-8efb-2496c37fb712.png)

   
Login screen
![screenshot](https://user-images.githubusercontent.com/52511856/67719136-88327500-f9d1-11e9-8585-378f7795e950.png)

**Comment by jlnr** [comment]
It looks like this has been fixed in #339. There has been not a greeter release since then, but the release process is being automated right now, so hopefully the fix will land soon.
