### ISSUE TITLE
Sometimes black screen after lock

### ISSUE THREAD

**Issue by mateHD** [elementary/greeter#381]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I'm using my notebook with two external displays (notebook lid closed, docking station, display ports). After I lock the screen (⊞WIN+L), I see a black screen, It doesn't "wake up" and I don't see the login screen.
If I open and close my notebook's lid, everything is okay, the monitors works again and I see the login screen.

## Platform Information
 - OS: elementary OS
 - OS: Juno
 - Lenovo x270, intel 620 integrated gpu

Please check what applies:
- [x] I'm using the latest released stable version

**Comment by supernoi** [comment]
This "black screen" also happens to me, from the second login.
For example, I start using the system, lock the system for lunch, when I return after logging in again, it takes between 30sec and 1 minute on the black screen.

OS: Elementary OS 5.0 Juno (updated today)

**Comment by mateHD** [comment]
I tried with open lid (notebook screen + 2 monitors) and now working perfectly. So the problem is the closed lid.

**Comment by otavioschwanck** [comment]
Duplcated from: https://github.com/elementary/greeter/issues/165

The only reason i dont use eOS =\

**Comment by mateHD** [comment]
I think it isn't the same problem. I tried to wait more than a hour and the login screen doesn't go back.
The time doesn't help. Lid open/closed does.
