### ISSUE TITLE
Port to latest g-s-d api

### ISSUE THREAD

**Issue by worldofpeace** [elementary/greeter#382]
## Describe the bug
We have this same issue that's in gala https://github.com/elementary/gala/issues/518, is it's pretty much the identical code in here.

**Comment by worldofpeace** [comment]
Actually, I didn't check if this actually fixed it.

**Comment by janxkoci** [comment]
Could this be also affecting #412 ?

**Comment by worldofpeace** [comment]
We should port fixes from https://github.com/elementary/gala/issues/518 if it hasn't been here already.

**Comment by worldofpeace** [comment]
> Could this be also affecting #412 ?

No, because you need to be using a different g-s-d api to have this issue, and you were on elementary OS which doesn't.

**Comment by worldofpeace** [comment]
I believe https://github.com/elementary/greeter/pull/420 and https://github.com/elementary/greeter/pull/421 fixed this.
