### ISSUE TITLE
Solution for ugly gray background in screen-lock

### ISSUE THREAD

**Issue by sysadmin-info** [elementary/greeter#392]
Hello,

Final solution with the wallpaper for the lock screen:

Thread:
https://www.reddit.com/r/elementaryos/comments/cwisd3/is_there_something_wrong_with_the_new_pantheon/

Tested on Hera 5.1 

Downloaded this: https://github.com/elementary/greeter/archive/master.zip

from https://github.com/elementary/greeter/

Extracted the zip to /tmp

I opened terminal, sudo -i, typed root password. Then run gimp as root (just type gimp in terminal), saved jpg file as png in greeter-master/data folder (replaced previous texture.png file).

Edited the SystemBackground.vala file located in /tmp/greeter-master/compositor/ 

sudo vi /tmp/greeter-master/compositor/SystemBackground.vala

Changed path from:
var texture_file = GLib.File.new_for_uri ("resource:///io/elementary/desktop/gala/texture.png");

to:
var texture_file = GLib.File.new_for_uri ("resource:///io/elementary/greeter/texture.png");

Installed all dependencies listed here:

https://github.com/elementary/greeter/blob/master/README.md

gnome-settings-daemon >= 3.27
how to check version in terminal: 
sudo gnome-control-center --version

Installed dependencies

sudo apt install -y libaccountsservice-dev libgdk-pixbuf2.0-dev libgranite-dev libgtk-3-dev liblightdm-gobject-1-dev libwingpanel-2.0-dev libx11-dev meson valac libmutter-3 libmutter-3-dev

Compiled as root 
cd /tmp/greeter-master
meson build --prefix=/usr
cd build
ninja
ninja install

It is working. Finally! Hell yeah!

**Comment by cassidyjames** [comment]
This is not really an issue report, so I'm going to close it. Yes, you can modify the source code and recompile it to change it; it's open source after all. :)

**Comment by knyzorg** [comment]
@cassidyjames Could we have an option to configure this? The vast gray is such an eye sore :(

Meanwhile, #358 is so pretty that I won't care about any possible performance issues.
