### ISSUE TITLE
Manual login card?

### ISSUE THREAD

**Issue by worldofpeace** [elementary/greeter#394]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Most other lightdm greeter provide a UI to manually login providing a username and password irrespective to the information provided by accountsservice. I believe there's actually a good reason to this. It's possible accountsservice and logind have a fit, and they present no users. The greeter would be empty of any user cards and the user would be unable to manually login as a basecase fallback.

I recall this being a ui during the greeter rewrite.

**Comment by tintou** [comment]
It's already available!
In `/usr/share/lightdm/lightdm.conf.d/40-io.elementary.greeter.conf`
Under `[Seat:*]` Add:
```ini
greeter-show-manual-login=true
```

**Comment by worldofpeace** [comment]
Ah, looking at https://github.com/elementary/greeter/blob/deb-packaging/debian/40-io.elementary.greeter.conf it's not switched on in the debian packaging.

This is an interesting setting
* https://github.com/canonical/lightdm/blob/442e38384037b3ac79896cd91ce38c3ea48b7a2a/data/lightdm.conf#L65

Thanks @tintou for the tip :+1:
