### ISSUE TITLE
Hide mouse cursor until is moved.

### ISSUE THREAD

**Issue by Blast-City** [elementary/greeter#395]
What do you think?

P.S: Sorry if it is duplicate.

**Comment by cassidyjames** [comment]
GTK currently hides the cursor when typing in native entries, but what's the advantage of hiding it completely until moved? It seems like that would be less accessible.

**Comment by Blast-City** [comment]
> GTK currently hides the cursor when typing in native entries, but what's the advantage of hiding it completely until moved? It seems like that would be less accessible.

Hi.
Its just an aesthetic opinion. When I think of a login screen I think of something that is supposed to be controlled by a keyboard. It looks a little bit off having the mouse cursor showing by default on one of the corners of the screen.
How does it work on Gnome and KDE? I don't remember seeing the mouse cursor on Unity. I might be wrong, thought. If other Distro's also do it I will close this issue.
