### ISSUE TITLE
Unable to type password in Greeter after booting

### ISSUE THREAD

**Issue by tomosaigon** [elementary/greeter#396]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
On boot, the keyboard on my laptop doesn't work to type in the password to the prompt in Greeter. Trackpad works and after fiddling/clicking around for awhile the keyboard will suddenly start working. 
(I haven't been able to find any pattern to the clicking activity that makes the keyboard start working)

Once the keyboard starts working, it will continue working if I log out and come back to Greeter.

### To Reproduce
1. Boot
2. Arrive at Greeter
3. Focus the password bar if not focused
4. Try to type anything but not see any results

### Expected behavior
Typing should show hidden password characters

## Platform Information
Please share a screenshot of the System Settings > About screen.
If you can't please share:
 - OS: elementary OS
 - OS Version 5.1 Hera
 - Hardware info
Dell XPS 9575

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by tomosaigon** [comment]
I believe it's a problem specific to this hardware and probably can't be fixed, only ameliorated, in Greeter.

My temporary workaround is to switch into tablet mode then back when logging in.

**Comment by jtrees** [comment]
I'm not so sure this is a hardware issue. I've started encountering this too on my desktop PC.

Since the greeter rewrite focus was always in the password box until about two week ago (estimated, my sense of time may be a bit off though :D).

Anyway, please re-open this.

**Comment by tomosaigon** [comment]
@jtrees If the problem is about the password field having focus or not then I believe it's a separate unrelated issue.

**Comment by jtrees** [comment]
> @jtrees If the problem is about the password field having focus or not then I believe it's a separate unrelated issue.

Oh ok.
