### ISSUE TITLE
Login is not proper, functions are disabled

### ISSUE THREAD

**Issue by killedBy11** [elementary/greeter#405]
There is no log issued for this, since it's a bug that occurs during usage. If I log in after boot-up, then log out, then login and log out again, repeatedly, at one poing the login is not proper. By that 'improper' I mean that up in the top right, where you can shutdown the system, the user still says 'Logged out' under the username. If I click on log out to attempt logging out and logging back in again the buttons in the popup don't work, I am not taken to the login screen again. Also shutdown, suspend and reboot buttons in the pop-up don't work and the only way to fix it is by running 'sudo reboot' in the terminal. Attached you have improper and proper login screenshots, watch the top right corner.

Improper:
![improperLogin](https://user-images.githubusercontent.com/39056361/73981379-c62d2680-493a-11ea-9b69-d3a7772d0c93.png)

Proper:
![properLogin](https://user-images.githubusercontent.com/39056361/73981398-ccbb9e00-493a-11ea-942b-501ee2924228.png)

**Comment by marco4mp** [comment]
That happens to me too. After the first "logout and login".

**Comment by cassidyjames** [comment]
Thanks for reporting this! It looks like another side-effect of the Cerbere issue we're investigating at https://github.com/orgs/elementary/projects/67.
