### ISSUE TITLE
"Installer" Session option on normal accounts

### ISSUE THREAD

**Issue by alex285** [elementary/greeter#418]
## Describe the bug
I enabled the Guest Logins from Settings, and then on my account login I get an option to use the "Installer Session" that doesn't work anyway
![ele-bug](https://user-images.githubusercontent.com/11244308/76680160-009b7a80-65ef-11ea-8d8d-729225626028.png)

I only noticed that after I enabled the Guest Logins, but when I disabled Guests, the option remained, so I'm not quite sure if it was there before and I had missed it

### To Reproduce
1. Go to Settings and Users
2. Enable "Guest Logins"
3. Restart to apply changes
4. See screenshot above

Perhaps related #384 and #273 

### Expected behavior
"Installer Session" shouldn't be displayed

## Platform Information
I'm using Daily PPA plus I have compiled a few things, but they should be irrelevant with that

**Comment by alex285** [comment]
aha, that was caused after I compiled and installed "[Installer](https://github.com/elementary/installer)" module; I uninstalled it and the "Installer" option was gone

so you may want close this, not very important bug :/

**Comment by davidmhewitt** [comment]
Yep, the installer repository/package provides a session, so I think this is expected behaviour.

It's not normal to have the installer installed after you've already installed the system.
