### ISSUE TITLE
Can't switch user sessions leaving active account in background; login screen is displayed at a lower resolution than the desktop's

### ISSUE THREAD

**Issue by dennismayr** [elementary/greeter#422]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
There are 2 problems I'm experiencing with the lockscreen while using the `nvidia-340` proprietary video driver:

1. Locking the screen while in the active user session brings the user back to the login screen; however, that login screen is displayed at a _lower_ resolution than the desktop's, as if somehow it weren't the original lockscreen instance.
This does **not** happen with the open-source `nouveau` driver, but its performance is a no-go for my current workflow at the moment.

2. I can't lock screen and log into another user account (leaving the previous user session open in the background like in Windows); entering the password brings up a brief black screen, then goes back to the login screen (with the glitch described on point 1 above).
I have to log out completely from the currently active user account before logging into another.

### To Reproduce
1. Log onto a user session
2. Lock screen with `Ctrl` `Alt` `Supr`
3. Check the current lockscreen resolution: it will be lower than the logged-in desktop's; in some cases, the mouse cursor is the classic Xorg `X` instead of the themed arrow
4. Try logging onto another user account and wait for the desktop to show up
5. You will be brought back to the lockscreen.

### Expected behavior
1. Log onto a user session
2. Lock screen with `Ctrl` `Alt` `Supr`
3. Check the current lockscreen resolution: it should match the desktop's
4. Logging onto another user account should open the account's desktop without killing the other active user session in the background

### Screenshots or screen recordings
I've recorded the on-screeen process of having my user session open, then pressing `Command-L` to lock the screen and go back to the greeter, attempting to switch to another user session and failing, finally going back to the open user session:
https://www.youtube.com/watch?v=_K0L1NCd16w
(note that this only happens with the _nvidia_ **proprietary** driver

## Platform Information
 - OS: elementary OS
 - OS Version:  5.1.4 Hera (fresh install, updated by May 9 2020)
 - Hardware info:
    * ThinkPad T410s
    * Intel® Core™ i5 CPU, M 540  @ 2.53GHz
    * Video: NVIDIA Corporation GT218M [NVS 3100M] (rev a2)
    * Video driver: `nvidia-340` (the only compatible proprietary driver for my onboard NVS3100M)
    * Kernel: 5.3.0-45-generic
    * Memory: 8Gb

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by dennismayr** [comment]
I recorded a short video of the described behavior, and posted the link within the problem description above.

**Comment by kenedyroger** [comment]
same problem here!

**Comment by dennismayr** [comment]
After looking for workarounds, I've come to the conclusion that it may be an _NVIDIA_-exclusive problem related to its proprietary legacy driver that have known _xrandr_ quirks that won't be fixed, as they have no interest or motivation to do so.

Therefore, I'll just close this issue and stick to the open-source drivers; `nouveau` now runs fairly well on older _NVIDIA_ hardware (NVS3100M), and works with `DRI_PRIME` as opposed to the legacy proprietary driver.
