### ISSUE TITLE
No HiDPI detection for Focal/Odin

### ISSUE THREAD

**Issue by danrabbit** [elementary/greeter#427]
We probably need to update something to do with GSD autostarts

**Comment by decathorpe** [comment]
I've been dealing with this for some time, and as far as I can tell, this has nothing to do with gnome-settings-daemon, but with the change to libmutter 3.36.

The reason being that gala built against mutter 3.28 had HiDPI working fine alongside settings-daemon 3.36, but gala built against mutter 3.36 doesn't do HiDPI anymore.

**Comment by decathorpe** [comment]
@davidmhewitt oh, that's a different issue then. I'll try to figure out what's going wrong on the fedora side ...

**Comment by danrabbit** [comment]
Gala isn't present on the Greeter :)

**Comment by tintou** [comment]
Fixed by #428
