### ISSUE TITLE
Right click in the password input field gives me a greyed out context menu

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/greeter#431]
Does the context menu have a function at this point in the login process? Or could it simply be removed?

**Comment by cassidyjames** [comment]
It is a standard GTK entry with a password hint set. This is exactly how all GTK password entries behave. If you highlight some text, the `Delete` option is sensitive. We could possibly remove it, but I'm not inclined to since it's a standard GTK behavior.

**Comment by danrabbit** [comment]
Yeah I agree. I'm going to close this as "Design conflict" since the behavior seems expected from a standard Gtk Entry
