### ISSUE TITLE
deb-packaging: rename io.elementary.greeter.whitelist -> io.elementary.greeter.allowed

### ISSUE THREAD

**Issue by worldofpeace** [elementary/greeter#449]
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Describe the bug
The old working has been deprecated https://github.com/elementary/wingpanel/pull/326 @tintou 

Another question I have is, is this file required and why isn't it installed by meson. In downstreams I see them having to ship this separately.

**Comment by danrabbit** [comment]
I don't think this is used anymore since indicators now have a concept of whether they're running in session or in the greeter. It can probably be removed safely

**Comment by davidmhewitt** [comment]
Closing as this was removed
