### ISSUE TITLE
Reuse mouse settings if only one user exists

### ISSUE THREAD

**Issue by marcoms** [elementary/greeter#451]
I have my cursor size set to the maximum for visibility and mouse sensitivity reduced, but in the login/lockscreen it uses the default mouse settings. Since I am the only user of the computer, can the greeter detect this and reuse my settings? I find it difficult to see the default-size cursor.

**Comment by mhabibi** [comment]
I also use the right button for my primary click but in the greeter in it uses the default settings and it's annoying :/
