### ISSUE TITLE
ERROR:  Dependency "accountsservice" not found, tried pkgconfig

### ISSUE THREAD

**Issue by jaaoelias** [elementary/greeter#473]
After using `meson build --prefix=/usr` 

I get
![Captura de tela de 2020-09-29 13-00-07](https://user-images.githubusercontent.com/51971271/94583372-be1c5100-0253-11eb-9371-b96b8c309ed8.png)

Log file:
[meson-log.txt](https://github.com/elementary/greeter/files/5300330/meson-log.txt)

After i insert the command `cd build` and then `ninja` and i get the error:

![Captura de tela de 2020-09-29 13-01-23](https://user-images.githubusercontent.com/51971271/94583680-1a7f7080-0254-11eb-9ade-b2c307e77694.png)

**Comment by davidmhewitt** [comment]
libaccountsservice-dev is listed as a dependency in the readme (amongst other packages). Did you install it?

**Comment by jaaoelias** [comment]
I forgot that, thank you ! it worked. Thank you
