### ISSUE TITLE
No HiDPI detection in greeter session on Odin

### ISSUE THREAD

**Issue by vjr** [elementary/greeter#486]
The latest `pantheon-greeter` package build on Odin as of a few hours ago is showing up LoDPI where prior to this is was HiDPI as expected.

Could this issue be similar/related to https://github.com/elementary/installer/issues/414 which was fixed by https://github.com/elementary/installer/pull/428 ?

Note the comment from the installer issue: https://github.com/elementary/installer/issues/414#issuecomment-595934887

**Comment by davidmhewitt** [comment]
As discussed in Slack, your display size/resolution combo does not normally trigger HiDPI detection anyway, you usually "force" pixel doubled by editing the gschema file.

I've just tried to reproduce this issue and editing the gschema file, compiling the schemas and rebooting has correctly "forced" pixel doubling in my greeter.

This is likely the result of some leftover files after installing from git without the `-Dubuntu-patched-gsd=false` option set for Odin.

**Comment by vjr** [comment]
Seems like a false alarm, there were a couple of greeter executables in /usr/local/bin and /usr/local/sbin which when I deleted, it resolved the issue.
