### ISSUE TITLE
Backports required for OEM/Initial Setup in Hera

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/greeter#490]
I believe we'll need to backport #455 and #465.

This should allow initial setup to set the keyboard layout in the greeter session so that passwords for new users can be typed with their chosen layout.

Likely need to resolve #489 first

**Comment by cassidyjames** [comment]
It looks like these are still outstanding, as I don't see them in the `juno` branch.

**Comment by danrabbit** [comment]
5.0.4 was successfully backported. Just did the cherry pick, waiting on import

**Comment by danrabbit** [comment]
Built!

**Comment by cassidyjames** [comment]
Thank you!
