### ISSUE TITLE
Music stops on lockscreen (EOS 6 Beta)

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/greeter#526]
I don't know if this is a bug or a part of how the system functions, but the music I am playing stops on the lockscreen whenever I let the laptop sit while listening to music and the screen dims, goes black then locks. 

Edit: Looks like a bug that was "fixed" with a reboot. Not sure

## Expected Behavior
An ongoing activity such as music should stay active even on the lock lockscreen.

**Comment by jeremypw** [comment]
There are several existing issues on the same or similar subject: #483, #461, #163, #61.  I believe work is ongoing to find a secure solution to this.

Please check existing issues for duplicates :wink:

**Comment by KarkanAlzwayed** [comment]
> There are several existing issues on the same or similar subject: #483, #461, #163, #61. I believe work is ongoing to find a secure solution to this.
> 
> Please check existing issues for duplicates 😉

Damn, I thought I searched pretty good. Lol.
