### ISSUE TITLE
Lock Screen Security

### ISSUE THREAD

**Issue by postnick** [elementary/greeter#546]
## What Happened

Opening Laptop - the unlock screen doesn't come back, so I have a black screen with a cursor. 
I can use gestures for multitasking and it shows what was last on my screen. If one had private information you could easily see what was left up on the computer. 

Also need to force shutdown to get back into EOS6. 

## Expected Behavior

I expect the lock screen to come back after i open my laptop lid. 

## Steps to Reproduce

1. Close lid OR Windows Key + L to lock screen. It may just never come back to the login screen. 
2. Unknown time and then open lid. Sometimes screen is black not the lock screen
3.Swipe up on multi task. 

SEE VIDEO LINK: [Video](https://photos.app.goo.gl/AJ3fEPRitcXZR2Za9)

## Platform Information

EOS 6 fresh install as of yesterday.

**Comment by o-alquimista** [comment]
It's probably a duplicate of #397.

This is an issue with LightDM upstream. It has been around for a long time :/

**Comment by almir-lima** [comment]
I Have same trouble, after last system update, i not can suspend or close screen from notebook without restart the system.
When i do login, the system start but back to screen login again, the solution is restart.

**Comment by dcowan-london** [comment]
I do successfully get the lock screen, but if I switch to tty7 (lock screen on tty8), I get this
