### ISSUE TITLE
Tick Color for Active User Doesn't Use Active User's Preferred Color

### ISSUE THREAD

**Issue by janga1** [elementary/greeter#555]
## What Happened
The password box accent color seems to adopt the preferred color of the current active user, while the tick (identifier of current active user) does not. See this picture:
![image](https://user-images.githubusercontent.com/35235201/130076561-8d4d75cc-1456-4d4c-8e03-d1a4e3f1866c.png)

## Expected Behavior
Same color for both elements.

## Steps to Reproduce
1. Log in as any user (not guest).
2. Lock computer (Superkey + L).
3. Observe Greeter screen.

## Platform Information
Elementary OS 6

**Comment by janga1** [comment]
I am not an avid programmer, but I will do my best to do some research.

What I've gathered so far:
1. The 'tick' icon is created in `src/Cards/UserCard` lines `216-218`. The problem is that this is a `Gtk.Image` and so it cannot change color, because it is an image.
2. I think that, _if_ we want to use user preferred accent color (**do we?**), the tick should look more like what it looks like in the _Appearance_ view of [elementary/switchboard-plug-pantheon-shell ](https://github.com/elementary/switchboard-plug-pantheon-shell) (See picture in repo `README`). This however, is a button... which might not be ideal, unless the button would be disabled or something.

**Comment by danrabbit** [comment]
If like to keep this open as it's a valid issue report. Probably the route to go here is some custom CSS

**Comment by janga1** [comment]
Sorry for closing. I figured maybe I was being overly meticulous.
