### ISSUE TITLE
Cannot properly resize installer window

### ISSUE THREAD

**Issue by haagensen** [elementary/greeter#632]
Installing OS 7, I'm trying to resize the installer window. Grabbing the window border with the mouse to the right, the window moved down (actually seems it always goes down no matter which direction I choose) to the point I couldn't see the buttons on the window anymore. 

Also, I couldn't find a way to move the window, either with the keyboard or the mouse. 

Had to restart the PC to make it usable again.

**Comment by danirabbit** [comment]
Transferred to Greeter because we use the greeter compositor in the installer session. This seems to happen because of setting “always center”

**Comment by peteruithoven** [comment]
Bit of a workaround for getting the window back: Pressing your windows key and then dragging the window.

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/installer/pull/717
