### ISSUE TITLE
Plank and Wingpanel absent when login

### ISSUE THREAD

**Issue by Faelian** [elementary/greeter#64]
Sometime, when I log in, I will have a mouse and the desktop background but no dock or top panel.

My workaround is to log into a tty, launch htop and kill `/usr/lib/gnome-sessiosn/gnome-session-binary --session=pantheon` with SIGKILL.
This will bring back the login screen, and after 2 or 3 try, I have a dock and a panel.

I have join some logs. I think lightdm.log could help you see the problem.
[log.zip](https://github.com/elementary/greeter/files/1207373/log.zip)

Please get in touch if you need other informations.

**Comment by matzipan** [comment]
I don't think this issue is related to Greeter, it seems like the user session is having difficulties starting up, but it's not clear from the lightdm log files what the problem might be.

**Comment by matzipan** [comment]
Closing as invalid. We can track on IRC or community slack where the bug might be coming from.
