### ISSUE TITLE
Feature Request: Support Wayland

### ISSUE THREAD

**Issue by Cameronsplaze** [elementary/greeter#646]
### Problem

It seems like as wayland is getting more developed, it's considered to be the more secure and modern of the two (vs x11). Would it be possible to support both display servers?

### Proposal

I see some comments in the code about supporting wayland some day. Is this on the table still?

[lightdm-elephant-greeter](https://github.com/max-moser/lightdm-elephant-greeter) did it via [Cage](https://www.hjdskes.nl/projects/cage/), so that is one option at least.

**Comment by BAProductions** [comment]
Ditto

**Comment by lenemter** [comment]
Hello. We have organization wide project to track Wayland support. Take a look at https://github.com/orgs/elementary/projects/118 and https://github.com/orgs/elementary/projects/99

**Comment by Cameronsplaze** [comment]
Oh that makes sense. Thank you!
