### ISSUE TITLE
Option to disable 'gear icon' session chooser

### ISSUE THREAD

**Issue by FunkySalamander** [elementary/greeter#647]
### Problem

I see since yesterday now there's a gear icon on the login screen.
I liked that previously it was so minimal that it would hide the available desktops from everyone.

### Proposal

I'd like to be able to disable it somewhere in the settings, I don't know if there's a config file or whatever to do that. In the case there isn't I wanted to submit this feature request to ask for it.

**Comment by tintou** [comment]
This is because you've installed a second environment in your computer, look at `/usr/share/xsessions/` for all the sessions you've available.
For instance, Ubuntu comes with the `ubuntu-session` package which isn't shipped by elementary OS.

**Comment by danirabbit** [comment]
Going to close this since this serves a purpose when multiple sessions are installed and the way to not see this UI element is to have only one session available
