### ISSUE TITLE
No user names visible at Pantheon Greeter until click 

### ISSUE THREAD

**Issue by jsalatiel** [elementary/greeter#69]
After updating to loki, at the login screen all users  are represented by blue icons. I don't see the login names behind the blue  icons until I click in the space behind the icon. (I have to click icon  by icon in order to find the correct user to login.) 
The name should be shown at the side of the icon, just like it used to be on elementary 0.3.
This is really bad for the usability on multi user systems.

I found at least two threads talking about the problem:
https://elementaryos.stackexchange.com/questions/8220/no-user-names-visible-at-pantheon-greeter-until-click
https://elementaryos.stackexchange.com/questions/11411/show-user-names-on-the-login-screen

**Comment by wilfil** [comment]
+1

**Comment by DrewBe121212** [comment]
+1

**Comment by yluckn** [comment]
Any news on this ? I am also facing this problem!

**Comment by lsrzj** [comment]
+1 and another observation, if you click on the icons itself, the user is not selected, so you have to click where the name should be shown, but it's hidden. It makes it very confusing to figure out how to select a user.

**Comment by jsalatiel** [comment]
This still affects Juno.  

![juno](https://user-images.githubusercontent.com/5522389/42849282-ee7ee96e-89f8-11e8-9a2f-df26a8196508.png)


See the old Freya way. User two and three can click directly in their user without try to guess which avatar they are.

![freya](https://user-images.githubusercontent.com/5522389/42849336-247de6be-89f9-11e8-997b-0c6f009e6880.png)
