### ISSUE TITLE
greeter-compositor exited with code 1

### ISSUE THREAD

**Issue by pimvullers** [elementary/greeter#700]
### What Happened?

Pantheon greeter crashes with Mutter 45.2; extended logging a bit (printing the command that exited)  revealed that it is the compositor process that exits with code 1.

Originally reported as https://github.com/pimvullers/elementary/issues/247

`** (io.elementary.greeter:12797): CRITICAL **: 20:30:42.493: MainWindow.vala:360: prompt: `Password: ' (1)

** (io.elementary.greeter:12797): CRITICAL **: 20:30:42.778: MainWindow.vala:360: prompt: `Password: ' (1)

** (io.elementary.greeter:12797): CRITICAL **: 20:30:43.852: SubprocessSupervisor.vala:48: io.elementary.greeter-compositor 

** (io.elementary.greeter:12797): CRITICAL **: 20:30:43.852: SubprocessSupervisor.vala:49: Child process exited with code 1`

### Steps to Reproduce

Experienced on Gentoo Linux with Pantheon Overlay (https://github.com/pimvullers/elementary):
1. Build greeter against Mutter 45.2
2. Start greeter
3. Wingpanel becomes visible, but nothing else
4. After some time everything goes black

### Expected Behavior

Greeter showing the login screen (same as with lower mutter version).

### OS Version

Other Linux

### Software Version

Compiled from git

### Log Output

```shell
** (io.elementary.greeter:12797): CRITICAL **: 20:30:42.493: MainWindow.vala:360: prompt: `Password: ' (1)

** (io.elementary.greeter:12797): CRITICAL **: 20:30:42.778: MainWindow.vala:360: prompt: `Password: ' (1)

** (io.elementary.greeter:12797): CRITICAL **: 20:30:43.852: SubprocessSupervisor.vala:48: io.elementary.greeter-compositor 

** (io.elementary.greeter:12797): CRITICAL **: 20:30:43.852: SubprocessSupervisor.vala:49: Child process exited with code 1
```

**Comment by bobby285271** [comment]
I wonder if you are also running into #682 🙃

**Comment by pimvullers** [comment]
Adding https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3329 as patch to the mutter package in Gentoo Linux indeed solves the problem. (this is the second fix @bobby285271 mentioned).

Closing as not a greeter issue, but upstream problem, and existing issue present.
