### ISSUE TITLE
 [eOS 8.0 daily build 20240219] User account is disabled on immediately after creating the account on first boot, requiring a reboot

### ISSUE THREAD

**Issue by truefakts** [elementary/greeter#708]
### What Happened?

Full disclosure, I'm running this in a VM. But I doubt that is related to this issue.

This bug occurred immediately after installing the latest daily build of eOS 8.0. It’s also an intermittent issue that I was about to reproduce only once during the installation of the 02072024 build. Essentially the user installs the operating system and powers down the machine to remove the installation media. They boot the computer back up, and they’re presented with the initial setup/out of box experience. Right after I define a username and password, typically you’re presented with the greeter which asks you to login. However on occasion, your account is shown as “disabled” and you have to reboot the machine in order to login.

### Steps to Reproduce

This is an intermittent issue, so it will be tricky to reproduce. I have followed these exact steps on 3 occasions and was only able to trigger this bug once. Also, this was tested using Gnome Boxes with the latest daily build of Elementary OS 8 running in a VM. This is what I did:

1. Install the VM using the default Ubuntu 24.04 profile that Gnome Boxes sets up for you. I selected UEFI instead of BIOS
2. Run through the installation, including multimedia codecs. No fancy partitioning, just the typically next next next install shutdown
3. After gracefully shutting down the VM, I shut down the host machine (had stuff to do. Likely unrelated)
4. Boot up the host machine, boot up the VM
5. Define my user account. Default selections for everything, (US locale stuff) and define a username + password
6. Right after clicking finish, observe that you cannot login to the account you just created (see screenshot)

This is an intermittent bug that I have only come across in the daily builds of 8.0, which I have been testing in a VM. Most of the time, this doesn't happen. Also changing the login selection from X.org to Wayland doesn't change anything
![elementary_os_first_login](https://github.com/elementary/greeter/assets/47705198/ea74f988-26d7-4b3b-bbe8-b0eb1a243d07)

### Expected Behavior

Basically what happens 99% of the time. The user is presented with the login prompt

### OS Version

Early Access

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

This was tested in a VM using Gnome Boxes in a flatpak

Host machine: (probably irrelevant)

    Linux Mint 21.3 Cinnamon Edition
    Linux drew-desktop 6.7.3-060703-generic #202401311935 SMP PREEMPT_DYNAMIC Thu Feb 1 00:46:47 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
    Ryzen 5 5600X
    RX 6600 XT
    16GB of RAM

VM running elementary OS

    OS: elementary OS 8 Early Access x86_64
    Host: KVM/QEMU (Standard PC (Q35 + ICH9, 2009) pc-q35-7.2)
    Kernel: 6.6.0-14-generic
    Uptime: 1 min
    Packages: 1736 (dpkg), 17 (flatpak)
    Shell: bash 5.2.21
    Resolution: 2560x1440
    DE: Pantheon
    WM: Mutter(Gala)
    Theme: io.elementary.stylesheet.mint [GTK3]
    Icons: elementary [GTK3]
    Terminal: io.elementary.t
    GPU: 00:01.0 Red Hat, Inc. QXL paravirtual graphic card
    Memory: 981MiB / 3896MiB

**Comment by danirabbit** [comment]
I can't confirm this with the latest build. Might have been a quirk of early builds
