### ISSUE TITLE
Not possible to activate virtual keyboard to enter password when using a touchscreen...

### ISSUE THREAD

**Issue by captennemo** [elementary/greeter#72]
I prefer to use a touchscreen now that I have one. When logged in all is working fine, but on "lock screen" I must connect a keyboard to enter my psw. I have configured the greeter to display keyboard (keyboard=onboard and virtual keyboard=true and things alike) with no luck.  Have also tried to compile an older version of Pantheon greeter and for ex. version 2.0.2 have this functionality so my guess is that it got "lost in translation" from 2.x to 3.x or something? From my point of view this is the missing piece of the puzzle to get rid of my keyboard.

**Comment by arjunmenon** [comment]
This is a significant accessibility issue. Most of these UX stuff were there in freya.

**Comment by offendo** [comment]
is there any update on this? I'm having the same issue and can't find any other sources for a solution

**Comment by offendo** [comment]
just found a workaround

1. install [`wingpanel-indicator-a11y`](https://github.com/elementary/wingpanel-indicator-a11y)
2. add `show-indicators=~a11y;~session;~power;<other-indicator-names>` to `/etc/lightdm/io.elementary.greeter.conf`

You can then manually toggle the keyboard from the icon menu when logging in. Obviously it's not perfect, but at least I can log in without attaching a keyboard now.

**Comment by davidmhewitt** [comment]
I've verified that this is already resolved in the elementary OS 6.0 images. The a11y indicator is installed and enabled by default in the greeter and I just powered on my laptop and logged in with the touchscreen (without touching the mouse/keyboard).
