### ISSUE TITLE
Coredump with Mutter14

### ISSUE THREAD

**Issue by danirabbit** [elementary/greeter#725]
### What Happened?

Greeter compositor coredump with Mutter 14

### Steps to Reproduce

Install an older OS 8 daily and upgrade mutter 13 to 14
or
try to boot current OS 8 daily

![Screenshot from 2024-04-18 14 10 27](https://github.com/elementary/greeter/assets/7277719/134d8884-5574-493c-9cce-d48ee124ef44)

### Expected Behavior

no dump :)

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by tintou** [comment]
Hopefully, this will be fixed with Mutter 46.1

**Comment by tintou** [comment]
It is related to an issue with the elementary cursor theme, when changing to Adwaita I see no issue

**Comment by tintou** [comment]
See https://gitlab.gnome.org/GNOME/mutter/-/issues/3454#note_2089722 which might be a reason

**Comment by danirabbit** [comment]
I can confirm with the latest icons build that it works now!
