### ISSUE TITLE
Login card is displayed in the installer session

### ISSUE THREAD

**Issue by ryonakano** [elementary/greeter#732]
### What Happened?

Login card (username and password input) is displayed under the installer window if I boot from the elementary OS 8 Early Access ISO.

### Steps to Reproduce

1. Boot from ISO (I used `elementaryos-8.0-daily.20240525.iso`)
2. Wait until installer window is shown
3. Move the installer window with Super + drag
4. See the login card of Live session user appears

![image1](https://github.com/elementary/greeter/assets/26003928/cc70d621-c353-4459-b3ff-a72935e83308)

![iamge2](https://github.com/elementary/greeter/assets/26003928/86b9e40f-a16e-4e70-8760-a4054cc994ab)

### Expected Behavior

Login card should not be displayed.

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment]
Reopening since #733 is reverted in #736.

**Comment by SubhadeepJasu** [comment]
This issue is related to #770 . Fixing that issue causes this issue to happen.
