### ISSUE TITLE
Installer window is not shown

### ISSUE THREAD

**Issue by ryonakano** [elementary/greeter#734]
### What Happened?

Installer window is not shown in the live session and just the wingpanel is shown:

![screen](https://github.com/elementary/greeter/assets/26003928/4129dddc-be1b-43c6-ad87-39b50806dc53)

### Steps to Reproduce

1. Boot from Early Access ISO (`elementaryos-8.0-daily.20240527.iso` is not reproducible but `elementaryos-8.0-daily.20240529.iso` is reproducible)
2. Wait until greeter launches
3. See Installer window is not shown

### Expected Behavior

Installer window is shown.

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment]
I'm not sure which Installer or Greeter causes this issue, so I submitted it here for now.

**Comment by danirabbit** [comment]
Haha okay so basically after https://github.com/elementary/greeter/pull/733 :sweat_smile:

**Comment by ryonakano** [comment]
Closing since #733 is reverted in #736.
