### ISSUE TITLE
Pressing power key should not cause a shutdown when users are logged on.

### ISSUE THREAD

**Issue by Djcoper** [elementary/greeter#74]
If I wake my system from suspend and accidentally press power key twice my system will proceed to wake up then immediately shutdown WITHOUT warning of logged on users, unsaved work etc...

**Comment by danrabbit** [comment]
I can't confirm this on elementary OS 6 beta2. It looks like pressing power on the greeter will suspend, not shut down. Since this is a fairly old report, this behavior probably was changed and this issue was fixed.

Closing as "incomplete" until someone else can verify this issue :)
