### ISSUE TITLE
Use palette api to shade background

### ISSUE THREAD

**Issue by btkostner** [elementary/greeter#75]
We should use the super awesome [palette API](https://github.com/elementary/granite/pull/122) to shade the background.

This will help with busy backgrounds to create a more solid color for the foreground to contrast.

This is also similar to what android 8.1 does as it's less intensive than using blur.

By shade I mean overlaying the prominent background color at like 0.4 opacity

**Comment by cassidyjames** [comment]
I guess this would supercede #19?

**Comment by danrabbit** [comment]
Closing since this is not really relevant anymore with the new design
