### ISSUE TITLE
Profile icon for guest user is confusing

### ISSUE THREAD

**Issue by josephholsten** [elementary/greeter#76]
On first login, it appears that the user profile icon is being accidentally displayed a second time below the login box. I believe that it's intended to be a way to log in as the guest user, though I'm not always successful in actually being able to use it.

I'm thinking my confusion would go away if we:
- said "Guest Sign In" similar to how my sign in box says my full name
- use a different profile icon, even just a grey version of the default

**Comment by cassidyjames** [comment]
Yeah, something we discussed at the GNOME design hackfest was that a guest session isn't really another user as far as the mental model is concerned, it's a mode. So separating it from the list of users would actually make more sense to me. I.e. a button at the bottom-left of the display.
