### ISSUE TITLE
Button to select session type without function

### ISSUE THREAD

**Issue by Letterus** [elementary/greeter#767]
### What Happened?

Currently, when you click the settings type button to select the session type (X11/Wayland), the button switches to activated state, but shows no additional view to select any session type. So you may only login to default session type.

### Steps to Reproduce

1. Boot or log out
2. Try to select a session type via the settings button - nothing happens.

### Expected Behavior

View to select a session type should appear.

### OS Version

8.x (Early Access)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Hardware Info

ThinkPad X280, i915

**Comment by ryonakano** [comment]
Strange, it should show the popover to select session type like this:

![Screenshot from 2024-10-12 17-23-52](https://github.com/user-attachments/assets/5849d9da-c4b4-493d-aab0-059940ccefd3)

Are you using dGPU like Nvidia?

**Comment by vjr** [comment]
I first experience this too today after updating. Intel 4th gen CPU with igpu here.

**Comment by Letterus** [comment]
> Are you using dGPU like Nvidia?

Thank you for your reply.

Intel Graphics, i915 driver as written above.

**Comment by danirabbit** [comment]
Hm, I thought maybe I fixed this but it's happening again here :thinking:

**Comment by Letterus** [comment]
I can confirm this is fixed by now. Very nice! :)
