### ISSUE TITLE
Installer UI is not centered

### ISSUE THREAD

**Issue by ZethiaZ** [elementary/greeter#789]
### What Happened?

While installing a daily ElementaryOS build (elementaryos-8.0-daily.20240328.iso) the installer's UI is not centered. I had the same issue months ago with a stable version of ElementaryOS 7, however I did not record it at that time. 

### Steps to Reproduce

1) Flash ElementaryOS iso to a USB drive with balena etcher.
2) Boot into the boot menu and select the default install/try ElementaryOS (not safe mode).
![IMG_20240407_152121_144](https://github.com/elementary/installer/assets/48283890/87977a59-c223-4403-9954-9ec2e46c9f06)

### Expected Behavior

I am fairly certain the UI is supposed to be centered and not off to one side.

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

I am using an Asus ROG Zephyrus G15 laptop that has an RTX 3060 Laptop Gpu alongside the integrated graphics in its Ryzen 6900HS.

**Comment by danirabbit** [comment]
Moving this to Greeter because we use the center protocol in installer now, just need to make sure the greeter compositor is updated to use it

**Comment by lenemter** [comment]
Moving to installer since greeter-compositor is still X11 and installer doesn't use our X11 protocol
