### ISSUE TITLE
Gray text in welcome screen is low contrast

### ISSUE THREAD

**Issue by D0J0P** [elementary/greeter#81]
Looking at the gray text in welcome screens such as this one: https://imgur.com/B3OTCYN where it says "Add a printer to begin printing" and in the gray box where it says "Search for the printer you need" is very low in contrast, and causes eye strain. I have to squint in order to read that text, and it hurts my eyes a bit.

An article from the NN/g I read that talks about low contrast text is a good read: https://www.nngroup.com/articles/low-contrast/

**Comment by jwinnie** [comment]
@D0J0P This is the repository for the the login screen. For UI components, you should file an issue at elementary/granite.

**Comment by danrabbit** [comment]
Closing as "Out of scope" since this was reported against the wrong repo
