### ISSUE TITLE
Broken HiDPI Profile Image Rendering

### ISSUE THREAD

**Issue by naftulikay** [elementary/greeter#84]
As originally reported [here](https://bugs.launchpad.net/bugs/1737848), I'm seeing my profile image rendered at one quarter of the size it should be:

![](https://i.imgur.com/v8iYrNd.jpg)

I was told that this was fixed, but I still see the issue on a fully updated Loki.

**Comment by danrabbit** [comment]
Closing as a duplicate of #62
