### ISSUE TITLE
Touchpad cannot be used to click

### ISSUE THREAD

**Issue by biswaz** [elementary/greeter#85]
I cannot use the touchpad to click on anything on the greeter screen. I have to use the physical buttons below the touchpad. Also, when I wake from sleep mode, the password field is not the active input. I have to point my cursor to the password field and click using my physcial touchpad button to make it active.

I'm using a HP 15 ac123tx laptop.

**Comment by biswaz** [comment]
I'm a noob to Linux. If anyone needs more debug information please let me know

**Comment by danrabbit** [comment]
This should be fixed as of this commit: https://github.com/elementary/default-settings/commit/c23cdfb5376279f4bb30ae4259dd36f266d6a1ce

**Comment by codygarver** [comment]
Not fixed.

**Comment by danrabbit** [comment]
@codygarver can you test it against https://github.com/elementary/greeter/pull/82 ? It's likely that master just doesn't load the correct settings in Juno

**Comment by danrabbit** [comment]
So it looks like this will be automatically resolved once #23 is resolved.

Marking as blocked since the problem seems to be the lack of compositor
