### ISSUE TITLE
Long login time

### ISSUE THREAD

**Issue by aramsichord** [elementary/greeter#86]
Hi,

There is an issue with my elementary os desktop. I get to the login and enter my password, and I have to wait a long time. Sometimes it feels like two minutes just with the wallpaper waiting for the desktop to load. Any ideas on how I can diagnose the issue? I have a lot of non-appcenter apps installed, and I'm thinking it may be one of them, but I don't know the best way to see what's going on immediately after login. Thanks!

**Comment by peteruithoven** [comment]
See: https://github.com/elementary/gala/issues/143

**Comment by peteruithoven** [comment]
Closing this as a duplicate of elementary/gala#143
