### ISSUE TITLE
Login screen wallpaper isn't changed

### ISSUE THREAD

**Issue by Djaler** [elementary/greeter#88]
When I change my user's wallpaper, wallpaper on login screen doesn't changed.

I make some debug. In this line https://github.com/elementary/greeter/blob/master/src/PantheonGreeter.vala#L199 `userlist.current_user.background` is null. So, looks like somewhere something did not written.

UPD: I am on Juno

**Comment by mdh34** [comment]
It looks like this is a bug with lightdm - `lightdm_user.background` returns null, but hardcoding a test path in it's place works fine
