### ISSUE TITLE
light-locker is broken on Juno

### ISSUE THREAD

**Issue by torikulhabib** [elementary/greeter#92]
can not lock screen
![screenshot from 2018-03-25 09-21-43](https://user-images.githubusercontent.com/26135527/37871029-f79aa6fe-300d-11e8-83f5-f1f57c39e493.png)

asus@asus-K46CA:~$ light-locker-command -l
** Message: 09:15:13.030: Received error message from the locker: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: This method is not implemented
asus@asus-K46CA:~$ light-locker-command -a
** Message: 09:16:37.186: Received error message from the locker: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: This method is not implemented

light-locker not working
please help me
Juno Beta

**Comment by danrabbit** [comment]
Unless you're a time traveler, you're certainly not running Juno Beta. Can we get your actual system information please? If you're installing development packages on another operating system, you should not expect to have a working system.

Closing as "incomplete"

**Comment by btkostner** [comment]
I'm also experiencing this with an alpha build.

```bash
btkostner@New-Caprica:~$ light-locker-command -l
** Message: 15:28:33.879: Received error message from the locker: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: This method is not implemented
```

```bash
btkostner@New-Caprica:~$ uname -a
Linux New-Caprica 4.15.0-12-generic #13-Ubuntu SMP Thu Mar 8 06:24:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
btkostner@New-Caprica:~$ light-locker --version
light-locker 1.8.0
```

![screenshot from 2018-03-25 15 31 06](https://user-images.githubusercontent.com/3385679/37880158-8f9f0f5c-3041-11e8-950f-7a82959b370f.png)

**Comment by codygarver** [comment]
Since we started using light-locker years ago I had to create a DPMS daemon to set values that light-locker expects/requires. However, it requires a patched GSD.

Since components are getting upstreamed to other distros, this has become a point of controversy.

I would like a cleaner way to accomplish the same goal but I have no idea what that is. I am holding off on "fixing" this bug for as long as possible.

Patched GSD: https://bazaar.launchpad.net/~elementary-os/elementaryos/os-patch-gnome-settings-daemon-xenial/revision/2

elementary-dpms-helper: https://github.com/elementary/dpms-helper/blob/master/bin/elementary-dpms-helper

**Comment by decathorpe** [comment]
Yeah, it would be nice to have a working screen lock without having to rely on gnome-settings-daemon patches (which I can't do on fedora, for example).

**Comment by codygarver** [comment]
Fixed by elementary/session-settings@b875272e16ec699c275fe0bfaf701b202951c4c3 and elementary/os-patches@af897c5788231d4f76dd2f00aaaa533905109e0e

**Comment by decathorpe** [comment]
Is there a way I can fix light-locker without having to patch gnome-settings-daemon?

**Comment by btd1337** [comment]
How to get this fix?

**Comment by btd1337** [comment]
This hotfix was it released? Because this error persists.


```
light-locker-command -l
** Message: 02:58:22.181: Received error message from the locker: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: This method is not implemented
```

**Comment by surajmandalcell** [comment]
Any updates? 
```shell
~ 
➜ light-locker-command -l
** Message: 20:45:23.309: Received error message from the locker: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files

```

**Comment by osiyuk** [comment]
Screen is not Locking for me either
```
$ light-locker-command --lock
** Message: 05:51:43.183: Received error message from the locker: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
```

**Comment by dennismayr** [comment]
It's unbelievable that this is still broken in Juno *release*.

I took the whole day to migrate my workflow from Loki, and basic stuff like this is still on alpha stage in January 2019.

**Comment by dennismayr** [comment]
Still happens in Juno *release*.
Fresh install, from scratch.

**Comment by peteruithoven** [comment]
@codygarver any idea why people might still be experiencing this issue?

**Comment by codygarver** [comment]
One situation where this can happen is if `gnome-screensaver` gets installed somehow, usually as a dependency of something else like `ubuntu-unity-desktop`. Try `sudo apt-get remove gnome-screensaver` and reboot if it was present.

**Comment by codygarver** [comment]
Just to be certain, you're experiencing this error message, right?:
```
$ light-locker-command --lock
** Message: 05:51:43.183: Received error message from the locker: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
```

Can you post a log of your installed packages?:
```
apt list --installed > installed.txt
```

It seems like something is preventing the lock from being possible, according to the error message, instead of being missing DPMS settings that set the timeout.

**Comment by dennismayr** [comment]
I'll check the logs tonight, as there's no message displayed, along with my currently installed packages.

Bear in mind that this happens with the default Juno installation, with or without additional system updates, restricted extras, and/or system updates.

**Comment by dennismayr** [comment]
As requested, `installed.txt`.
[installed.txt](https://github.com/elementary/greeter/files/2761908/installed.txt)

**Comment by dennismayr** [comment]
About the error message:

```
$ light-locker-command --lock
** Message: 20:38:53.425: Received error message from the locker: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
```

It's the same message.

**Comment by codygarver** [comment]
Hrm, I don't see anything obvious in the installed packages that could be breaking this.

I'm curious what hardware others who are experiencing this issue have.

In the meantime, I recommend you write an email payment@elementary.io and ask for a refund.

**Comment by dennismayr** [comment]
I'll leave my hardware specs here, it may help pinning down the problem cause.
[lshw-ThinkPad-T410s.txt](https://github.com/elementary/greeter/files/2775761/lshw-ThinkPad-T410s.txt)

**Comment by pridumkuvatyj** [comment]
@codygarver, I also have the same situation with locker. My system is a bit littered(I've been trying `gnome-desktop`), but `gnome-screensaver` is removed. Anyway I couldn't lock the screen on a fresh Juno release install too. Attaching my hardware list also if it helps.
Thanks!
[hwinfo.txt](https://github.com/elementary/greeter/files/3014073/hwinfo.txt)
[installed.txt](https://github.com/elementary/greeter/files/3014074/installed.txt)

**Comment by dennismayr** [comment]
The problem occurs while using the `nvidia-340` proprietary driver; the open-source `nouveau` driver doesn't cause this problem, but its performance is a no-go for the purpose of this laptop.

GPU is an NVidia NVS3100m

**Comment by worldofpeace** [comment]
Is this still an issue? It seems very stale (@tintou maybe you could close this)

**Comment by dennismayr** [comment]
There are 2 problems I'm still experiencing while using the `nvidia-340` driver:

1.- Locking the screen brings the user back to the login screen, right? Well, that login screen is at a _lower_ resolution than the desktop's, as if somehow it weren't the original `light-locker` instance.
2.- I can't lock screen _and_ log into another user account; entering the password brings a brief black screen, then goes back to the login screen (with the glitch described above). I have to log out completely from the current user account before logging into another.

If this behavior should be described in another ticket, I can do so.

Thanks for looking into this! :smile:

**Comment by worldofpeace** [comment]
> There are 2 problems I'm still experiencing while using the `nvidia-340` driver:
> 
> 1.- Locking the screen brings the user back to the login screen, right? Well, that login screen is at a _lower_ resolution than the desktop's, as if somehow it weren't the original `light-locker` instance.
> 2.- I can't lock screen _and_ log into another user account; entering the password brings a brief black screen, then goes back to the login screen (with the glitch described above). I have to log out completely from the current user account before logging into another.
> 
> If this behavior should be described in another ticket, I can do so.
> 
> Thanks for looking into this! smile

Thanks. All of that sounds different than the op. It also seems they're considering replacing light-locker, but depending on the severity of the issues they could issue a bugfix still.

**Comment by dennismayr** [comment]
@worldofpeace Will do. Thanks for looking into it!

**Comment by cassidyjames** [comment]
Closing as we've not had recent reports that match this issue, plus we've had significant greeter and session changes since it was reported. New issues can of course still be reported or this one can be re-opened if it's still relevant.

**Comment by dennismayr** [comment]
Ok, as per @worldofpeace's suggestion, I've opened a related ongoing issue with the current greeter
https://github.com/elementary/greeter/issues/422

**Comment by bubersson** [comment]
I'm getting the same error now when clicking on the lock button or when using keyboard shortcut. 

Here's some debug info:

```sh
OS: elementary OS 5.1.7 Hera x86_64
Kernel: 5.8.5-050805-generic 
```

```sh
$ journalctl --since "2 min ago"
Sep 29 23:57:05 dude wingpanel[14742]: session_widgets_userbox_update_state: assertion 'self != NULL' failed
Sep 29 23:57:07 dude wingpanel[14742]: Indicator.vala:163: Unable to lock: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
```

```sh
$ light-locker-command -V
light-locker-command 1.8.0

$ light-locker-command -q
** Message: 00:22:43.618: Locker is not running!
```


During restart I get

```sh
Oct 01 20:55:15 dude light-locker[2132]: The program 'light-locker' received an X Window System error.
                                        This probably reflects a bug in the program.
                                        The error was 'BadValue (integer parameter out of range for operation)'.
                                          (Details: serial 180 error_code 2 request_code 26 (core protocol) minor_code 0)
                                          (Note to programmers: normally, X errors are reported asynchronously;
                                           that is, you will receive the error a while after causing it.
                                           To debug your program, run it with the GDK_SYNCHRONIZE environment
                                           variable to change this behavior. You can then get a meaningful
                                           backtrace from your debugger if you break on the gdk_x_error() function.)
```

And then when trying to lock with ctrl+L

```
Oct 01 21:04:52 dude gsd-media-keys[2005]: Couldn't lock screen: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
```
