### ISSUE TITLE
Logging out and in again causes failure to log out again or shutdown (Juno)

### ISSUE THREAD

**Issue by jeremypw** [elementary/greeter#98]
Not sure if the right component to file this against but ...

To reproduce:

* Log in (tested with an administrator account)
* Immediately log out
* Log in again (same user)
* Try to log out or shut down - nothing happens.  The session does not end - i.e. apps run OK.  Running `sudo shutdown now` in a terminal shuts the computer down immediately.

Occasionally requires more than two logins to occur (e.g. if started in recovery mode).  On the second login there is a delay before plank and wingpanel appear.

Investigation so far indicates that after the second login, the process `dbus-launch` is still running and there is an additional dbus-daemon.

Ending the `dbus-launch` process causes the session to end and the login screen to appear. Shutdown or restart from here is successful.  Logging back in from here usually causes wingpanel and plank to not appear at all.

**Comment by ryonakano** [comment]
I can reproduce this many times. Also, sometimes I didn't need to immediately log out. At that time, I logged in and used OS just as usual. Then once I logged out, this issue happened.

**Comment by jeremypw** [comment]
This seems to have improved very recently - I can usually close down OK on logging back in although there are still two dbus-daemon processes running and it takes much longer for the desktop to appear when logging back in (and for shutdown to complete).

**Comment by jeremypw** [comment]
After more investigation, I now have to log out and back in *twice* to trigger this bug - at which point there are 2 dbus-launch processes and 3 dbus-daemon processes (!)

**Comment by danrabbit** [comment]
@jeremypw can you still reproduce this with the new Gtk+ greeter? I can't seem to reproduce it any longer

**Comment by jeremypw** [comment]
I cannot reproduce this now, although there is a different bug - after logging in the second time the desktop does not appear until I close and re-open the lid.  I'll close this and reopen a different report if necessary.

**Comment by Schyken** [comment]
I'm currently able to reproduce this bug on my machine. Clicking log out from the power button drop-down in Wingpanel does nothing, and the same happens with the log out prompt when pressing `Ctrl`+`Alt`+`Delete`.

This is reproducible between different users. Other menu items do seem to work for me such as switching user by clicking on another user profile.

```
elementary OS 5.0 Juno
kernel 4.18.0-22-generic
AMD Ryzen 7 2700 (16) @ 3.400GHz
Nvidia Corporation Device 2184 (GTX 1660)
```

**Comment by danrabbit** [comment]
@Schyken are you using the greeter from git master?

**Comment by Schyken** [comment]
I am not, but I can certainly try that and see if it changes anything.

>

**Comment by Schyken** [comment]
It seems the reply I sent afterwards via email hasn't arrived... The new greeter doesn't seem to be exhibiting this behaviour after a few hours of testing. I am under the impression that it is likely fixed. Sorry for not checking that first!

**Comment by scotthews** [comment]
I'm new to Elementary and have installed 5.1 and the above behaviour is definitely happening.  Have tried across multiple accounts and the same occurs.  Log in, sometime later log out and back in again.  You know the issue will occur as it takes it a long time to log in.  If the log in is quick then all is fine.  However, if the login time is slow (black screen appears for 30 seconds or more after entering your password) then you cannot use the wingpanel to Sleep, Log out, shutdown etc.  It seems as though Alt-Ctl+Del is the only option.

**Comment by wernerd** [comment]
I also see this behaviour - any solution to this? I also notice that wotkspace settings (using gesttings) are not honored anymore. I use 

- gsettings set org.pantheon.desktop.gala.behavior dynamic-workspaces false
- gsettings set org.gnome.desktop.wm.preferences num-workspaces 6 

but nothing happens. Could tese two issued be related?

**Comment by cassidyjames** [comment]
As an update to anyone following this issue: we're investigating this. It seems that cerbere (our daemon to start and restart shell components) is not closing cleanly, which causes issues in the session once you log out and back in.

**Comment by ghabit** [comment]
Sorry if it is bad to post on closed issues, but I have same bug. Cannot logout sometimes.

**Comment by g-arjones** [comment]
As far as I understand, the issue was confirmed by @cassidyjames . Why is it closed?

**Comment by cassidyjames** [comment]
There are a number of duplicate issues, and it appears the issue is not with the greeter itself. You can check the linked GitHub Project board for the latest.

**Comment by g-arjones** [comment]
Great. Thanks
